### ISSUE TITLE
Sticky bookmark

### ISSUE THREAD

**Issue by 4tron** [alefragnani/vscode-bookmarks#10]
Would be a nice feature to be able to make the bookmarks sticky to the original line of code when the bookmark was first added. After a while of coding all my bookmarks make no sense anymore.

**Comment by Terminux** [comment]
This feature it also a must have to me. I would like to know if you started to work on it because i worked on it in my [fork](https://github.com/Terminux/vscode-bookmarks). You can take a look or i can make a PR.

**Comment by alefragnani** [comment]
I didn't started yet. I priorized other features and right now I'm working on #8 . But feel free to work on it and send a PR. I will be glad to merge it when it's done :smile: 

I was wondering how to manage the line changes, and your idea is interesting. I didn't test it but I looked your code. It may have two issues when the `lineCount` doesn't change:

- _Pasting text_ (same line count) over an area that already contains a Bookmark (which should remove the Bookmark)
- _Move lines_ should move the Bookmark.

When the issue was posted, I thought to look at VSCode itself, and see how it handles _Breakpoints_, at least to have an idea. 

Thank you for your cooperation. I will be waiting for you PR :+1: .

**Comment by Terminux** [comment]
Great. I continue to work on it then. Thanks for the (little :smile:) review.

**Comment by alefragnani** [comment]
Thank you for helping with this :+1:

**Comment by Nimzozo** [comment]
I have this issue too. After a lot of changes, my bookmarks are not on the good lines of code I placed them initially. (If I had 5 lines before the bookmark, it is then 5 lines too early.)
