### ISSUE TITLE
Default to true for "bookmarks.navigateThroughAllFiles"

### ISSUE THREAD

**Issue by hadrien-psydk** [alefragnani/vscode-bookmarks#102]
Hello,

Thank you for your excellent extension. Bookmarking is a feature I was missing in VS Code.

I am opening a feature request to suggest setting "bookmarks.navigateThroughAllFiles" to true by default. I have no problem if you disagree with it, but I have been using Notepad++, Sublime Text and Visual Studio (the full IDE) and it seems they all default to cross document navigation for bookmarks. I think it would be less surprising for a new user to get cross document navigation too by default in VS Code + your extension.  I spent myself some time finding the right setting.

Best Regards,

**Comment by alefragnani** [comment]
Hi @hadrien-psydk ,

Thanks, I'm glad you like!

I understand you, and I'm starting to think that yes, it should be `true` by default. I have closed another issue (#21) in the past, but by now, maybe I could change that.

Thanks for remembering that suggestion

**Comment by virzen** [comment]
I second this, I thought it's a bug and only through this issue I've found the settings to enable it. For me jumping through all files was the expected behavior from the very beginning.

**Comment by nikitavoloboev** [comment]
I disagree with it being a default behavior. But it's great to have a setting for it.

**Comment by andrea-maruccia-leaseplan** [comment]
I expected also this to be the default and I could find that info only by coming here. I would suggest to update the doc as a minimum. 
![image](https://user-images.githubusercontent.com/65156073/85941399-065d6780-b923-11ea-8565-60491a8f30d2.png)

**Comment by SergeyBeloglazov** [comment]
I have used VSC about 1.5 year and everything was fine till now. I was so close to removing this extension as broken.... 
I have use Notepad++ and other IDEs for 20 years, and have never ever seen if bookmark navigation move me to another file.
I think, more predictable behavior for new user is navigation only inside current file.
For bookmarking files I use a "favorite" extension.
You may leave the default behavior as it's now, but please, write it clearly in the features, that jumping is performing through all files by default.
Thank your for the extension!

**Comment by alefragnani** [comment]
Hi @SergeyBeloglazov ,

I"m coding for about 20 years too, with a lot of different Editors and IDEs, and it's funny to think that I never liked to use the _unlimited bookmarks_ feature they provided. I loved Delphi approach, with only 10 bookmarks per file, individually defined with its own keyboard shortcuts. In the end, I used the same file based concept here. 

But, since the beginning, some people asked to have a workspace based navigation, and I added. It was a new feature, and I decided to leave `false` by default. Then, a lot of people complained because didn't noticed the setting. Make it `true` by default considered the amount of issues opened about it.

Deciding default value for setting is always a pain. Leave as it is, and people don't see the new feature. Use the new value, and current users may dislike. 

But I understand your point, the docs can be improved to make it clear, and will be,

Hope this helps

**Comment by SergeyBeloglazov** [comment]
> But I understand your point, the docs can be improved to make it clear, and will be,

Thank You!
The first thing I did - went to description page, didn't see anything about jumping inside one file or though all the workspace.
I decided at first it works only the one way, and it doesn't suit for me. Later found an option.
Anyway the option is great, everybody can be happy! :)
