### ISSUE TITLE
color display text?

### ISSUE THREAD

**Issue by boyvinall** [alefragnani/vscode-bookmarks#105]
Hi, thanks for the extension, I don't use it very often, but it's absolutely brilliant when I have to deep-dive on a new codebase. 

One suggestion - is it possible to syntax-highlight the text?  or at least at some sort of color.  My window currently looks like this:

![image](https://user-images.githubusercontent.com/1652176/39304193-cfb41ff6-4950-11e8-8444-1be46a228e62.png)

I think I'd find it a lot easier to use if there was some sort of color to aid visual differentiation between different lines.  Syntax highlight would be good if possible, but maybe even just a different background on the filename line would probably help.

**Comment by alefragnani** [comment]
Hi @boyvinall ,

I agree! It would be much easier to recognize each line of code. But unfortunately, it is not possible, yet, to customize how the treeview is presented. I can't change node's color, font or style. 

Otherwise, I see an improvement that could be made, based on GitLens extension's idea. Add a `< >` symbol around the line numbers, just for quicker diferentiation between the line and its position.

Thanks for your suggestion

**Comment by alefragnani** [comment]
Hi @boyvinall ,

In the latest release of the extension, I have updated the Treeview with a new line preview content. Instead of `< >` for cursor position, as I previously commented, I decided to use `( )`, moving it to the end of the line preview / bookmark label. Please, take a look.

About the _syntax highlighting / coloring_, the API limitation remains the same, and I don't see that changing in the near future. When some new API appears, I'll reopen the issue.

So, I'm closing it for now...

**Comment by boyvinall** [comment]
Thanks! Will check it out soon.
