### ISSUE TITLE
Allow new shortcuts: Ctrl-Alt-L locks desktop on Ubuntu

### ISSUE THREAD

**Issue by alexrosabr** [alefragnani/vscode-bookmarks#110]
It would be nice to change the shortcut in the settings.

**Comment by alefragnani** [comment]
Hi @alexrosabr ,

You can do that directly in VS Code, using `File / Preferences / Keyboard Shortcuts`, and choose the shortcut that better fit you needs.

I'm sorry, but I cannot change the default shortcuts, because it would break every current user that uses the default shortcuts. To avoid that scenario in the future (different OS, Keyboard Layouts), I decided do avoid shortcuts on new commands/extensions. The user will have to choose/define.

Hope this helps

**Comment by alexrosabr** [comment]
OK, that will do. Thanks.
