### ISSUE TITLE
Enable Naming of Bookmarks

### ISSUE THREAD

**Issue by Orrison** [alefragnani/vscode-bookmarks#111]
This extension is amazing and so useful, thank you so much for taking your time to write it.

It would be perfect if just for the ability to name your bookmarks. It's great that you can come back to the code and have various bookmarks around for important things but it would be awesome if they could be named with a little not to help remind you what they are.

Thanks again!

**Comment by pakLebah** [comment]
I hope you'll find your free time as soon as possible, because we really need this feature when we're working on large codes with tons of bookmarks. If somehow you can't find your free time, perhaps you should call 911 to get some helps. I hope your free time is alright. 😄

**Comment by Orrison** [comment]
@alefragnani Sounds good! I totally get it! Take care of yourself and your priorities man, sorry for not noticing the other issue and making a duplicate.

Thanks again for all your time put into this project, you're awesome!

**Comment by alefragnani** [comment]
@pakLebah I wish 911 could pay my bills 😄. I love developing these extensions, and I'll keep doing that, but right now I need to focus on projects that can help me with that matter. 

I also work with large projects. At least, I think 17k files of source code means _large_ 😄 . That's one of the main reasons Bookmaks are so important to me. I never had _labeled bookmarks_ available on my development workflow, but the day the issue was created, I realised it was a good thing.

@Orrison don't need to be sorry about the duplicate, it's fine. I'm here to help

**Comment by alefragnani** [comment]
I think you would like to know that I have already started the development of these features, a couple of weeks ago, but I didn't have enough free time to finish.

I'll post a video (at the original thread) of the current development status of the features, so everyone could comment if it's going in the right direction. Maybe this way, I could get some backers for the feature.

Thanks for you support
