### ISSUE TITLE
Thank you for new version! But the label UX is confusing.

### ISSUE THREAD

**Issue by pakLebah** [alefragnani/vscode-bookmarks#124]
Hi,

I just fired-up my VS Code when I saw a notification of an extension update. It's Bookmarks! It's been a long waited update. Congratulations! 😊

Overall, it's a great update. Love the new features. However, IMO, you need to fix the user experience of label feature. I'd say it's a bit confusing, to say the least. Why do I need to toggle a label? Label is not a state, it's an information. When I run the feature for the first time on a bookmark, the bookmark gone missing from the panel. So, I saw 3 bookmarks on the editor's gutter but only saw 2 bookmarks on the bookmarks panel. It's weird.

![jepretan layar 2018-07-13 pada 21 58 09](https://user-images.githubusercontent.com/11470932/42698382-efc739f2-86e7-11e8-922f-b4e685e57e8d.png)

As far as I could understand, it seems that you provide 2 kind of bookmarks. Regular bookmark without label and labeled bookmark which each has its own toggle command, at least sometimes they act like that. What if I want to label an existing bookmark? Toggle it and toggle it again using `Toggle labeled` command. CMIIW.

My suggestion is to remove the `Toggle labeled` command altogether. Just use the familiar `Toggle` command. If we want to put a label into a bookmark, simply go to the Bookmark panel, double-click the bookmark we want to label, type the label, press Return, done. Or provide `Edit label` command through the panel submenu. If we want to remove label of a bookmark, simply edit it and enter empty string, or provide `Remove label` command through the panel submenu.

I also think the pencil icon inside the label text is unnecessary. It takes valuable space in the panel. You could simply use different style to label text, such as brighter color or bolder font weight. The line and column info could also be simplified as `(line:col)` e.g. `(234:10)` instead of `(Ln 234, Col 10)`.

What do you think? 😊

**Comment by alefragnani** [comment]
Hi @pakLebah ,

First of all, thanks. It has been the biggest update of all my extensions, and it wasn't easy to do.

About the missing bookmark, I don't know what could be. I tested the _data migration_ a lot, but I'm not sure if this has to do with _migration_. Please let me know if something else happens.

The `Labeled Bookmark` UX was the most basic idea that I could find, because I never used this kind of bookmark. It certainly could improve. I liked your ideas, thanks 👍 Let's wait for other feedbacks to see how it could be....

Thanks

**Comment by pakLebah** [comment]
Here's what happened:

![bookmarks_bug](https://user-images.githubusercontent.com/11470932/42741560-ab530416-88dd-11e8-8c9f-2212e48c9b17.gif)

Simply doing both **Toggle** and **Toggle labeled** on the same line would left the bookmark's mark on the gutter while the actual bookmark is no longer there. What I really want to do is putting a label onto the already available bookmark. That's what I called _confusing_.

**Comment by mbcrawfo** [comment]
@alefragnani I agree with @pakLebah that two different types of bookmarks is a bit confusing.  I would argue that there should only be "labeled bookmarks," just have the label text default to the contents of the bookmarks line and allow users to edit the label if they wish.

**Comment by alefragnani** [comment]
An UX prototype is reported in #137 .

**Comment by alefragnani** [comment]
Hi @mbcrawfo ,

Thank you for your suggestion, but it wouldn't be possible to use the _bookmark line_ as default value, because the bookmark is based in _line number_ and not _its contents_. Do you remember when you delete/add lines, the bookmark _moves up/down_? 😃 

As I commented in #137, _"I'm still not convinced about using a single command. For me, the labeled bookmark is a secondary option, so it should be an alternative command."_ 

So for now, it remains as two different commands, unless some new idea or proposal appears.

Hope this helps

**Comment by pakLebah** [comment]
We understand that bookmark is based on the line number and not the content. Labeled bookmark is just adding a comment onto a bookmark. It's still a bookmark nonetheless, not something else. If a bookmark doesn't have a label then the content of the line is used as the label, just like they way it worked before. Labelling a bookmark _should not be a command_, but _an option_ to existing bookmarks. So, it's still a single command: put a bookmark. Label is a second thought.

Just my 2¢. 😊

**Comment by mbcrawfo** [comment]
@alefragnani Honestly I don't think default label matters much when you have the ability edit the label.  For example Visual Studio simply numbers bookmarks by default (Bookmark 1, Bookmark 2, etc).

**Comment by nealot** [comment]
Adding a context menu option like "edit label" seems like a much better idea. I also agree with most of the arguments in this conversation.

Can there be an option to remove the ": (line:col)"? It just seems really unnecessary because if I wanted to know the line and column I'd just visit the bookmark.

**Comment by alefragnani** [comment]
Hi,

The new version is out for a while, and based on feedbacks, I'll be make two updates.

1. I'll be adding a `Edit Label` command to the Activity Bar. This will be tracked in #146.
1. I'll not add _customization_ of the line/bookmark preview, but instead, a simpler `on/off` option. This will be tracked in #143.

So, I'm closing this issue, in favor of these other two.

Hope this helps
