### ISSUE TITLE
Automatically create bookmarks from comments

### ISSUE THREAD

**Issue by zpaolo11x** [alefragnani/vscode-bookmarks#128]
I don't know if it's feasible... would it be possible to define a custom comment token (like "//BM") so that the line starting with that is automatically bookmarked? That would actually "embed" the bookmark in the code, and add it to the bookmark list on every different editor when working on different machines.

**Comment by liamrosenfeld** [comment]
`MARK: - ` is a standard for comment bookmarks, [Xcode even natively supports it](https://littlebitesofcocoa.com/207-annotating-swift-with-marks-todo-s-and-fixme-s). It would be really nice to have functionality inside the bookmarks extension.

**Comment by alefragnani** [comment]
Hi @zpaolo11x @liamrosenfeld ,

First of all, thanks for your suggestion.

Its an interesting feature, but I think it goes a bit _out of scope_. Mostly because the extension is based on _user defined positions_ for its bookmarks, and in this case, it should become a _parser based_ approach.

But, don't worry, because there are already some other extensions that does what you suggested. Here are some that I found:

- https://marketplace.visualstudio.com/items?itemName=MattiasPernhult.vscode-todo
- https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
- https://marketplace.visualstudio.com/items?itemName=minhthai.vscode-todo-parser

Hope this helps

**Comment by zpaolo11x** [comment]
Wow @alefragnani thank you for the quick response... I didn't know those extensions, I looked for bookmarks and I should've looked for "ToDo" apps. I managed to tweak ToDo-Tree and Highlighter to do what I needed :smiley:

**Comment by essentdev** [comment]
I think that this feature would be a really nice complement to this great extension!
