### ISSUE TITLE
Ctrl+Alt keybindings on Windows

### ISSUE THREAD

**Issue by csholmq** [alefragnani/vscode-bookmarks#13]
![image](https://cloud.githubusercontent.com/assets/1297882/13001161/40837866-d163-11e5-8149-df04332a43a7.png)

Both Notepad++ and Atom uses F2. Set/Unset with e.g. Shift+F2 and then F2 to jump between.

**Comment by alefragnani** [comment]
Yes, I remember that, but `F2` and `Ctrl + F2` are already used as  **Code** commands:

```
{ "key": "f2",                    "command": "editor.action.rename",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+f2",               "command": "editor.action.changeAll",
                                     "when": "editorTextFocus" },
```

I tried to use `Ctrl + Shift + K` instead, but it was already being used as `editor.action.deleteLines`, so I ended up using the actual combination `Ctrl + Alt` + `K` to toggle, `J` and `L` to navigate. Besides this warning in console, the keybindings works fine.

But, the good about **Code** (just like **Atom**) is that you can define you own keybinds, as described in [https://code.visualstudio.com/docs/customization/keybindings](https://code.visualstudio.com/docs/customization/keybindings). 

Hope this helps.

**Comment by csholmq** [comment]
That's true. But as Ctrl+Alt can block special characters on non US keyboard layouts, perhaps the defaults should avoid that?

**Comment by alefragnani** [comment]
Hm, I didn't know the warning message was about that, I'm sorry. Since it was working fine for me (on a Windows Machine), and didn't find any docs about that, I thought it was some kind of _false positive_. I will take extra care next time when choosing keybindings.

I understand your point, but what about the users that already installed the extension? If I change the default keybinding, the extension _will stop working_ for them :disappointed: . Personally, I have no problem about changing the keybidings for `shift+alt` for instance, but as I said, I'm worried with the current users.

I will try to contact VSCode team, asking them for an advice on how I could handle this. Maybe they have a workaround that could handle existing users.

Thanks

**Comment by csholmq** [comment]
Here's some more info. https://blogs.msdn.microsoft.com/oldnewthing/20040329-00/?p=40003

There's also some work being done in Chromium to solve this;
Intent: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/Znyl5a96oDc
Issue: https://code.google.com/p/chromium/issues/detail?id=263724#c41
Blocker: https://code.google.com/p/chromium/issues/detail?id=168971
Blocker: https://code.google.com/p/chromium/issues/detail?id=227231
Blocker: https://code.google.com/p/chromium/issues/detail?id=527111

**Comment by alefragnani** [comment]
Some ideas:

1. Display a message right after updating the extension, asking if they want to keep the old keybinding, or replace with the new. Because only add this info in the Readme wouldn't be enough.
1. Create different Keybindings depending on Keyboard Layout https://github.com/Microsoft/vscode/issues/1240

**Comment by alefragnani** [comment]
There is no ETA for the VS Code API to be available, and so, I'm closing the issue.
