### ISSUE TITLE
Make lines in bookmark explorer configurable via format string

### ISSUE THREAD

**Issue by mbenkmann** [alefragnani/vscode-bookmarks#145]
Different people use bookmarks differently and will want to see different things in the bookmark explorer. I for instance do not care about column (I see bookmarks as a per-line thing) and little about the line number. But I would like to see at least part of the code at the line.

In order to please everyone I suggest to implement a format string similar to printf. E.g.

    %L (Ln %l, Col %c)

would correspond to the current display (%L = label, %l line number, %c column number).

    %04l: % 20C %L

would print the line number, 0-padded to at least width 4, followed by the code at the bookmark label padded with " " (note the " " between % and 20) or truncated as appropriate to 20 characters, followed by the label.

**Comment by alefragnani** [comment]
Hi @mbenkmann ,

Thanks for your suggestion! I agree that different people uses things differently, but instead of creating such complexity, just for the line preview, I prefer #143, which is much simpler. It handles two kind of users, those that want to see the information (using the same pattern from the statusbar), and those that don't want to see the information.

I hope you could fit in one of these two users 😄

**Comment by mbenkmann** [comment]
#143 only requests being able to remove line and column. I don't really care about that. What is an absolute must-have for me is an excerpt of the code on the line the bookmark is on. One of my typical applications would be to set a bookmark "TODO test this". With or without line numbers, these bookmarks are pretty worthless if I'm not able to see some code context in the explorer.

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
