### ISSUE TITLE
Save bookmarks between sessions

### ISSUE THREAD

**Issue by Nimzozo** [alefragnani/vscode-bookmarks#15]
Set to `true` by default is more logical in my opinion.

**Comment by alefragnani** [comment]
Hi, I understand, but since this setting wasn't released in the first version, I prefered to defined it to `false`, protecting the current users from _behavior changes_. I think that doing so, is _safer_ for the users, because he can _chose_ to use new features that can impact it its daily use.

Thanks for your suggestion.
