### ISSUE TITLE
Keyboard shortcut with LiveShare extension

### ISSUE THREAD

**Issue by equiman** [alefragnani/vscode-bookmarks#156]
`bookmarks.jumToPrevious` has the same keyboard shorcut as `liveshare.join` and because liveshare is down bookmarks overwrites the definition.

I solved adding this on keybinding.json 
```
{
    "key": "alt+cmd+j",
    "command": "-liveshare.join",
    "when": "liveshare:state != 'Joined' && liveshare:state != 'Shared'"
}
```

I don't know if will be good thinking in others combination on feature because don't believe that Microsoft gonna change it.

**Comment by alefragnani** [comment]
Hi @equiman,

Yes, I noted that in the latest releases of LiveShare extension, and I had to do the same thing to be able to use my shortcuts. 

In my opinion, this is a LiveShare issue, because the Bookmarks extension is older, and has this shortcut since day one. In fact, is _me_ who is not going to change anything :-D

Just to let you know, to avoid conflicts and keyboard layout issues, I had decided (almost two years ago) to not define new shortcuts in any of my extensions. I think MS, and any other extension developer, should do the same.

Hope this helps
