### ISSUE TITLE
 Ctrl+Alt+l is printing the symbol "." Also It's difficult to remove in VScode.

### ISSUE THREAD

**Issue by mariyappan88** [alefragnani/vscode-bookmarks#163]
Ctrl+Alt+l This shortcut works for "Selection to Next" but it is printing the symbol "." Also It's difficult to remove this. I don't know what is this and Why its printing (.)

**Comment by alefragnani** [comment]
Hi @mariyappan88 ,

This is probably caused by a conflict with your current **Keyboard Layout** and/or **OS**. 

You just have to re-assign another keybinding. Unfortunately, there is no _fix_ available, because there is no way to define different keybindings based on Keyboard Layout and/or OS.

BWT, the keybindings were created using US Internation keyboard layout, on Windows.

Hope this helps
