### ISSUE TITLE
Next or Previous bookmarks not working

### ISSUE THREAD

**Issue by fallXone** [alefragnani/vscode-bookmarks#17]
Using the next or previous bookmark either via the hot key, or selecting from the list, is not working. It doesn't seem to do anything. I have this same exact problem with another library of yours (project manager). Seems like the same issue.

**Comment by alefragnani** [comment]
Which **Code** version are you using? The newer release (extension) which contains the `List` command requires version **0.10.8** _(January release)_. But the `Jump to` commands worked since the first **Code** version.

Also, which _keyboard layout_ are you using? As you can see in issue #13, the `Ctrl + Alt` keybinding appears to be a problem with non US layout. At least it could explain why the keybindings are not working, but not the execution from the `Command Palette`.

Besides being a similar issue from **Project Manager** extension (not working), the reason differs. In Project Manager, the problem (for Mac) is the _startup architecture_ that **Code** uses, which doesn´t work like in Windows.

Hope this helps

**Comment by fallXone** [comment]
I am using Version 0.10.8, all default layouts. It doesn't appear to only be the keybinding, even clicking the item in the list or pressing enter on it does nothing. Running Windows 8.1

**Comment by alefragnani** [comment]
So, are you able to `toggle`, `list` and `clear` Bookmarks? 
What kind of file are you editing, and the number of lines?

I created another extension called **Numbered Bookmarks **. Could you install and check if it works. It has a different approach to _store bookmarks_, but similar to _navigate_, his could help me to understand what is going on.

Thanks in advance.

**Comment by fallXone** [comment]
@alefragnani nevermind you can probably close this out. This is only within one file? I thought it would work over multiple files

**Comment by alefragnani** [comment]
I get it :+1: . 
This will be handled in the near future (issue #8).
