### ISSUE TITLE
my vs code terminal isn't working

### ISSUE THREAD

**Issue by Wisdom132** [alefragnani/vscode-bookmarks#184]
whenever i try to use my vscode terminal it doesn't respond

**Comment by alefragnani** [comment]
Hi @Wisdom132 ,

Have you tried to use VS Code without any extension (`code --disable-extensions`) or disabling just this one (`code --disable-extension alefragnani.Bookmarks`), to see if the problem still occurs? 

This extension does not do anything with the Terminal, so it's weird that it stop working because of it. You probably have another extension, or VS Code itself, having issues with Terminal.

Hope this helps
