### ISSUE TITLE
Issue when moving a line up with alt + up arrow when line was selected with pointer

### ISSUE THREAD

**Issue by alnico2001** [alefragnani/vscode-bookmarks#186]
Reproduce error:

1. Make sure at least one bookmark is set in the file.
2. Select a line using the 'flipped right' pointer from the line bar (just left of the number). 
    Note: selecting the line manually and moving it does not produce the error.
3. With line selected, press alt + up arrow
4. Results: line will move up, but line immediately looses focus; then focus jumps two lines down.

**Comment by alefragnani** [comment]
Wow, that's weird 😆 

Thanks por reporting

**Comment by alefragnani** [comment]
Hi @alnico2001 ,

I was looking for this issue and I think it is not caused by this extension. I disabled it and the problem remains. 

Could you double check it?

**Comment by alnico2001** [comment]
I've double checked; issue still remains, but I know a little more that may help.

When selecting with the flipped pointer...notice that it selects the line(s) AND places the flashing cursor at the beginning of the line directly below the selection.  
You can manually make this same selection too.
Then move the line(s) up in either scenario and the jump occurs.

Also, if you select the last line, the cursor of course stays on the same line (at end of line).  
Moving the bottom line up does not cause the jump.

**Comment by alefragnani** [comment]
Well, if you disabled the extension and the issue remains, it’s not caused by it. You may have other extension that is responsible for it. You should disable one by one to properly identify which one is responsible. Start looking for extensions that would handle text formatting, selections or navigation.

Just out of curiosity, do you have my other [Numbered Bookmarks](
https://marketplace.visualstudio.com/items?itemName=alefragnani.numbered-bookmarks) extension installed? I know that it has similar issue (still under review). 

Hope this helps

**Comment by alnico2001** [comment]
Sorry, forgot to mention...yes I've disabled all extensions and tested (when I first reported the problem and today).

Tested with all extensions disabled (no problems).
Enabled Bookmarks and tested (problem occurs).
Disabled Bookmarks (no problems).

No, I do not Numbered Bookmarks installed.

Running on Windows 10

**Comment by alefragnani** [comment]
In this case, we are out of luck, because I see the issue even with the extension disabled (or my other extension enabled). Maybe some VSCode setting is the root cause.

I’ll try another scenarios, and let you know if I find anything
