### ISSUE TITLE
Tooltip when hovering the scrollbar mark

### ISSUE THREAD

**Issue by Nimzozo** [alefragnani/vscode-bookmarks#19]
It would be good to have a little preview when hovering the mark of a bookmark on the scrollbar.

I hope this is a doable feature.

**Comment by alefragnani** [comment]
Interesting idea :+1: 

I will take a look if is possible.

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/3698

**Comment by mbenkmann** [comment]
Does this issue also track the feature of getting a popup when hovering over the GUTTER (i.e. the left side of the code)? Right now it's difficult to read the label of a bookmark. The bookmark explorer seems to be the only place, so when I encounter a bookmark in the code, I have to take note of the file and line number and then go to the bookmark explorer and search for the bookmark with that line number. There should be some way, hover or click on the gutter icon that will show the bookmark label.

**Comment by alefragnani** [comment]
Hi @mbenkmann ,

No, it does not track hovering the gutter, but it would also depend on another VS Code issue https://github.com/Microsoft/vscode/issues/28080.

I'm closing this issue because both the VS Code issue that it depends on, has no update from VS Code team members for almost two years. Both are planed on "Backlog" Milestone, but it does not appear to be released soon.

I'm subscribed to both issues, so if/when it is closed, I'll be notified.

**Comment by alefragnani** [comment]
Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.
