### ISSUE TITLE
About shortcuts of bookmarks in activity bar

### ISSUE THREAD

**Issue by MuYunyun** [alefragnani/vscode-bookmarks#197]
Because of a personal hobby, I hide the activity bar. How about providing shortcuts to show bookmarks instead of click activity bar? 

![image](https://user-images.githubusercontent.com/19354791/55043805-cdc14500-5072-11e9-9651-04dfd902fb78.png)

**Comment by alefragnani** [comment]
Hi @MuYunyun ,

I have a mixed feelings about the Activity Bar. Sometimes I need it, sometimes I hide it 😄 . 

Either way, I have decided sometime ago to avoid defining new shortcut for any commands on my extensions. Basically because of these kind of issues:

* VS Code itself releases an update, and decides to use one of my shortcuts with a new native command
* Conflicts with different Keyboard Layouts/Languages
* Conflicts with native commands on different OS 

Personally, I use shortcuts a lot, but these issues drives me crazy.

But, you can do it yourself, using `Open Keyboard Shortcuts (JSON)` and adding the code below. You just have to `Reload Window`:

```json
    {
        "key": "ctrl+alt+b",
        "command": "workbench.view.extension.bookmarks"
    },
``` 

Hope this helps

**Comment by MuYunyun** [comment]
you are right,:smile: thanks for your application.
