### ISSUE TITLE
Code Folding 

### ISSUE THREAD

**Issue by Tengxuerong** [alefragnani/vscode-bookmarks#198]
My vs code can't appear icon of  collapse expand code block.I make it unload and download it again.But it still not appear icon of collapse expand code block.And my operating system is ubuntu.I hope you can give me some help.

**Comment by alefragnani** [comment]
Hi @Tengxuerong ,

Are you experiencing an issue in Code Folding after you installed the Bookmarks extension? 

The extension should not interfere in Code Folding. In fact, the bookmark icon is drawn on a separate area (together with Breakpoints), so it should not raise any problem.

Try disabling the extension, to see if the problem remains. If yes, the problem may be from another extension, or even VS Code itself

Hope this helps

**Comment by Tengxuerong** [comment]
Thank you for your reply @alefragnani 
I not installed the Bookmarks extension, I ask this question beacause my vs code appear this problem.
My English is poor,I don't know if you can understand my answer.
However,thank you

**Comment by alefragnani** [comment]
No problem. I'm asking because this is the repo of the Bookmarks extension, not VSCode itself :-)

Anyway, the Code Folding depends on Indentation OR Language (file type). Unless an issue in VSCode is responsible for that, it will depend on the extension for the file type you opened.

Which file type are you using? JS, Java, C#, Python?

**Comment by Tengxuerong** [comment]
My file type is JS

**Comment by alefragnani** [comment]
JS is handled by VSCode, unless you installed another extension. And it appears to support _Language Powered Code Folding_ instead of _indentation_, so unless your code has some compiling error, it should work.

![code-folding-example](https://user-images.githubusercontent.com/3781424/55050249-726d6380-502e-11e9-904d-d5e61a0bf8d8.gif)


Just out of curiosity, how is configured `"editor.folding"`, `"editor.foldingStrategy"` and `"editor.showFoldingControls"`?

I've found [this issue](https://github.com/Microsoft/vscode/issues/68499) in VS Code repo, If this is not your case, I suggest you to report this issue in VS Code repo. Maybe someone else has experienced the same issue, and could give you the right direction.

Hope this helps

**Comment by Tengxuerong** [comment]
![2019-03-27 15-43-11屏幕截图](https://user-images.githubusercontent.com/48267152/55058948-881f6f00-50a8-11e9-8f13-9c89cef40c14.png)

**Comment by alefragnani** [comment]
Well, in this case, I think its probably a bug in VS Code. 

Please fill an issue directly in VS Code repository [https://github.com/microsoft/vscode/issues](https://github.com/microsoft/vscode/issues). They will be able to help you with more information

Hope this helps

**Comment by Tengxuerong** [comment]
ok,Thank you very much for your help.
