### ISSUE TITLE
All commands not working with 10.4.1

### ISSUE THREAD

**Issue by jamilraichouni** [alefragnani/vscode-bookmarks#199]
Example:
"command 'bookmarks.toggle' not found"

When installing 10.4.0 it works.

Running VSCode:

Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by alefragnani** [comment]
Hi @jamilraichouni ,

There is probably some issue with the installation process (maybe the file was corrupted while installing), because there is no "real" difference between versions 14.0.0 and 14.0.1. It's just a _documentation_ update.

Please, try to reinstall it again, but first, be sure to uninstall and close all VS Code instances (instead of simply updating). Then you open VS Code again and reinstall it. It _should_ work

Hope this helps

**Comment by jamilraichouni** [comment]
Thanks, that helped:
What I did:

- Uninstall the extension
- Close VSC
- Open VSC
- Install the extension (version 10.4.2!?)
- Close VSC
- Open VSC
- Test command "bookmarks.toggle"
- Success
