### ISSUE TITLE
how do i use this? how do i create a bookmark?

### ISSUE THREAD

**Issue by cubetronic** [alefragnani/vscode-bookmarks#200]
there's no information whatsoever on how to create a bookmark.

i was hoping i could just click to the left of the line number, but that doesn't do anything.

it's installed and enabled. the activity bar shows a bookmarks explorer.

in "Details" it says...
> Manage your bookmarks
Toggle
You can easily Mark/Unmark bookmarks on any position.

how?! by doing what, exactly?

`Version 10.4.1, VSCode 1.32.3`
maybe this version is totally broken. i have no idea. i've never used this before. i'm new to VSCode. i'm used to Notepad++

**Comment by alefragnani** [comment]
Hi @cubetronic ,

The information is in the extension's page (README file), section [Available commands](https://github.com/alefragnani/vscode-bookmarks#available-commands). 

You toggle a bookmark using the `Bookmarks: Toggle` and `Bookmarks: Toggle Labeled` commands, and jump/move to a bookmark using the `Bookmarks: Jump to Next` and `Bookmarks: Jump to Previous` commands. You may also use the context menu (right click button).

> i was hoping i could just click to the left of the line number, but that doesn't do anything.

It doesn't use this approach (yet) because VS Code does not _support/publish_ this for extensions.

Hope this helps

**Comment by cubetronic** [comment]
Right-click on a line | Bookmarks: Toggle
Ctrl+Alt+K
View | Command Palette... | >Bookmarks: Toggle
Ctrl+Shift+P | >Bookmarks: Toggle

those are the actual commands
none of those were in the documentation

the documentation does appear to be in the VSCode documentation style, which is abstract documentation specific to VSCode but meaningless anywhere else

**Comment by alefragnani** [comment]
The _standard_ way to use VS Code is based on `Command Palette`, and the extension`s documentation lists, and describes, all available commands ]here](commands). 

I won't add shortcuts anymore because it would require specific info for Win/Linux and MacOS (because of the `Ctrl`/`Cmd`) differences. Also, different keyboard layout needs to override the default keybindings. The context menu is a _bonus_, which neither VS Code itself documents 😄 (but I do have in Changelog, btw).

I don't know which _VS Code documentation style_ you are referring to, but yes, the extension's documentation does not follow. 

Feel free to send a PR to update the documentation's _content_ (adding the right-click command reference). The _style_ on the other hand, won't change soon, because I have to apply the same style to all my other extensions as well.

Hope this helps

**Comment by soma115** [comment]
Ctrl+Shift+P is only information lacking in documentation. I like your extension @alefragnani Thank you.

**Comment by alefragnani** [comment]
Hi, 

Just out of curiosity, `Ctrl + Shift + P ` is for Windows/Linux. On MacOs you should use `Cmd + Shift + P`. You can also use `F1`, on any OS. At least on my keyboard layout.

That’s the main reason I don’t add this complexity/dependency to my extension’s documentation anymore, neither keyboard shortcuts. 

Imagine they change/add other ways, or add more OS, like ChromeOS? I would be forced to update every extension, and I don’t want that.

Hope you understand.
