### ISSUE TITLE
Typing delay/lag when SaveBookmarksInProject enabled

### ISSUE THREAD

**Issue by sni** [alefragnani/vscode-bookmarks#202]
When i enable the option to "save bookmarks in projects" typing is delayed heavily. If you type a word you can then see the word appearing slowly character by character. By slowly i mean maybe 100-200ms delay per character.
If i disable this option, everything is ok. It seems to only happen when the "vscodevim" plugin is enabled as well.

**Comment by alefragnani** [comment]
Hi @sni ,

I never noticed this issue, even for large projects, but I agree there must be some places for improvement in the extension. I don’t know, however, if these improvements could make big difference in your scenario, but I’ll take a look 👍 .

But, as you described _it seems to only happen when vscodevim is enable_ you should also open an issue in their repo, because maybe the bigger delay may be there. I don’t use vscodevim, so I don’t know how it works and what it does (which could delay typings).

Hope this helps

**Comment by sni** [comment]
The only occurance of this setting seems to be in `loadWorkspaceState()`:
https://github.com/alefragnani/vscode-bookmarks/blob/e3ff05d251ab0d24026c35af32ef39c604f1b8c4/src/extension.ts#L288
and that one is started from `activate()` which sounds like it should run only once.

But you are right, i created an issue for the vim plugin as well: https://github.com/VSCodeVim/Vim/issues/3666

**Comment by alefragnani** [comment]
In fact, the setting is also used  in `saveWorkspaceState()`, which may be called quite frequently (every text change which updates bookmarks positioning)  :

https://github.com/alefragnani/vscode-bookmarks/blob/e3ff05d251ab0d24026c35af32ef39c604f1b8c4/src/extension.ts#L321

This piece of code, I’m sure would be improved a bit, specially the synchronous file operations. 

Try downgrading vscodevim, as suggested by the comment in your issue. Let me know any new findings...

**Comment by sni** [comment]
i just checked, downgrading the vimplugin does not change anything. Is `saveWorkspaceState` called on each keystroke?

**Comment by alefragnani** [comment]
It _shouldn't_, unless the keystroke changes a bookmark position, in this case, the `row`, because the _sticky_ behavior is attached to rows only. But it appears this is not being respected, and every keystroke is calling `saveWorkspaceState`. 

I'll take a look if this could be easily changed (no side-effect), and release an update, so you could check if the lag changes.

Stay tuned

**Comment by sni** [comment]
great, thanks.
