### ISSUE TITLE
can not remove breakpoint

### ISSUE THREAD

**Issue by pig-peppa** [alefragnani/vscode-bookmarks#218]
Issue Type: <b>Bug</b>

can not remove breakpoint, when breakpoint in same raw with bookmark

Extension version: 10.4.4
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alefragnani** [comment]
Hi @pig-peppa ,

This is a know issue, already reported in #56, but as you can see in the comments, it’s caused by VS Code. So, it depends on VS Code team solving https://github.com/microsoft/vscode/issues/5923 for you to be able to have Breakpoints and Bookmarks (and any other decoration) in the same line.

Hope this helps.

**Comment by pig-peppa** [comment]
thank you for help me🤝,and thank you for make is plugin
