### ISSUE TITLE
Auto-save bookmarks by default

### ISSUE THREAD

**Issue by JVimes** [alefragnani/vscode-bookmarks#22]
I expect my bookmarks to be there when I close/reopen the program. It would be nice if they auto-saved.

**Comment by alefragnani** [comment]
Hi @JVimes ,

As I posted in #21 , I prefer to keep the same behavior of previous version when new features are added. The `"bookmarks.saveBookmarksBetweenSessions"` setting was added in the second release, and also, since it requires `load` and `save` while activating/executing, I preferred to avoid any performance issue for unaware users.

Thanks

**Comment by alefragnani** [comment]
@JVimes , for instance the issue #10 , when added, will also be _configurable_, and turned off by default. Firstly because it changes the default behavior that the user already know, and secondly because it needs extra processing (performance), just like the issue #8 .

I hope you understand my point :smile: 

Thanks

**Comment by JVimes** [comment]
Users don't want the same behavior as before (it's annoying right now). If you're worried about performance, release a beta version. Just a thought.

**Comment by alefragnani** [comment]
For me, in fact, is right the opposite. In my daily work (with _other tools_), if I save my _workspace_ to _restore the previous state_ it would take a couple of minutes to load the project again, which annoys me. So, I prefer a clean workspace when reopening projects. But, thinking about the others, I added this feature :smile: 

About the beta version, I wanted to do that, but at the beginning **Code** wasn't checking the `engine` field prior to installing extensions, so If I released a beta version, for instance in the _Insiders_ version, everyone would install it. But I will think about it in the future. Maybe using the _insiders_ or a _warning message_ in `readme` and after a while, releasing the feature **on** by default.

Thanks for your suggestion.

**Comment by JVimes** [comment]
If auto-saving bookmarks takes more than a few milliseconds then the implementation is pretty bad. Auto saving is done each time bookmark state is saved. Not sure what you're describing.

**Comment by JVimes** [comment]
Bookmarks have to be what, a few kilobytes at most?

**Comment by alefragnani** [comment]
As I wrote, I prefer to keep the same behavior as previous version, and let the user _decides_ to turn it on. That was the_main_ reason.

About the code being good or bad, if you look, you will see that it has nothing special. At least until today, no user complained about performance.
