### ISSUE TITLE
Advice and suggust : How can I open the input to enter commands

### ISSUE THREAD

**Issue by YangXinxiang** [alefragnani/vscode-bookmarks#222]
I can see the input area for typing commands in the read me , but I do'nt know how to open the input area.
Would you please tell me how to open that input box?

And I cannot see Shortcut keys information in the  read me. Would you please put the shortcut keys information for bookmark  in read me?

Thanks very much.

**Comment by alefragnani** [comment]
Hi @YangXinxiang ,

> I can see the input area for typing commands in the read me , but I do'nt know how to open the input area. Would you please tell me how to open that input box?

I think you are talking about the `Command Palette`, right? If that is the case, hit `F1` and you are ready to go. I suggest you to take a look at [VS Code documentation](http://code.visualstudio.com/docs) in order to master it. 

> And I cannot see Shortcut keys information in the read me. Would you please put the shortcut keys information for bookmark in read me?

Sometime ago I decided to avoid using (and documenting) shortcut keys on my extensions, basically because:

- Mac uses `Cmd` instead of `Ctrl`
- Conflict with OS native shortcuts (like `Ctrl + Shift + L` in some Linux distros is used to lock session)
- Conflict with different keyboard layout 

Thank you for your suggestions, but right now I have no intention to add those infos to the readme.

Hope this helps
