### ISSUE TITLE
Add shortcuts list

### ISSUE THREAD

**Issue by todorpr** [alefragnani/vscode-bookmarks#223]
I have used to shortcuts, but can't see anywhere a list of these for all the commands.

Would love to see it added.

**Comment by alefragnani** [comment]
Hi @todorpr ,

Sometime ago I decided to avoid using (and documenting) shortcut keys on my extensions, basically because:

- Mac uses `Cmd` instead of `Ctrl`
- Conflict with OS native shortcuts (like `Ctrl + Shift + L` in some Linux distros is used to lock session)
- Conflict with different keyboard layout

So, if you want to know the available shortcuts, you can open the `Command Palette` and filter the commands typing `Bookmarks`. It will show you all commands and the available shortcuts (on your machine).

Thank you for your suggestions, but right now I have no intention to add those infos to the readme.

Hope this helps

**Comment by todorpr** [comment]
Alright, thanks.
Great extension, congrats!

One more question - is is possible when navigating amongst the breakpoints "Jump to next" to NOT be limited to a single file. Reason - when working in a bigger project you normally touch several files, so such a transition by the shortcuts would speed up the process quite a bit.

I have in the past worked with WebStorm and this is one of the few features that I've been missing since I switched to VSCode.

**Comment by alefragnani** [comment]
Thanks you @todorpr!

Yes, you can do that. You just have update your User Settings, defining  `bookmarks.navigateThroughAllFiles` to `true`.

Hope this helps

**Comment by todorpr** [comment]
Amazing! Thank you, @alefragnani!

**Comment by q2apro** [comment]
Shortcuts are an essential part of every documentation / readme.

They should **definitely** be listed!

**Comment by alefragnani** [comment]
Hi @q2apro ,

> Shortcuts are an essential part of every documentation / readme. 
> They should definitely be listed!
> I just see the new context menu which shows them, still, put them into the docs.

I respect your opinion, but I’m sorry to say that I still won’t add them to the README file, for the reasons that I already pointed out. I will not _invest/waste_ time and effort checking each OS/keyboard layout to be properly documented, if I only have Windows/QWERTY/Western available. In my opinion, it’s too much effort for a _still_ free/open source project. 

If you really need them documented, feel free to send a Pull Request, but instead of changing the README file, use similar idea from the VSCode team, which just last year (if I remember correctly) has created a complete documentation for each OS (https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference).

Hope this helps
