### ISSUE TITLE
Mark result of search

### ISSUE THREAD

**Issue by yaute74** [alefragnani/vscode-bookmarks#235]
Hello,

Is there a way to mark all lines corresponding to a search ?
With ctrl+shift+L we can select the result of a search, but how mark all lines corresponding to a search ?

Regards,
yaute

**Comment by alefragnani** [comment]
Hi @yaute74 ,

If you are talking about search "inside a file", it's not available yet, but is already being tracked in #77 . 

But if you are talking about "Find in File" command, I'm sorry to say, but it probably never happen, because the VS Code team does not provide and API to "extend" that command, as reported in #7 .

Hope this helps.

**Comment by yaute74** [comment]
it's the first case, good news.
Thanks for your work, I close
