### ISSUE TITLE
Bookmarks in files with the same names.

### ISSUE THREAD

**Issue by asuhanov-ru** [alefragnani/vscode-bookmarks#236]
Then i add unlabeled bookmarks in files with the same names, there is a strange behaviour, extensions replace existing bookmark with the yet added.If labeled, all fine, but there are a lot of "index.tsx" in explorer :( If it possible, plise add some different view in explorer by label will be good?

**Comment by alefragnani** [comment]
Hi @asuhanov-ru ,

I'm not sure about the "strange behavior" that you are refering to. The bookmarks are _toggled_ ON/OFF for a File/Position (line based). It doe not _replace_ bookmarks from different files, just because the filename.

Be aware that the bookmarks follow a On/Off approach. There is no separate commands to `Add` / `Remove` bookmarks. So, if you Toggle a bookmark twice on the same file/line, it will _remove_ the previously added bookmark.

About the _different view_ that you suggest, I aggree that with a lot of _same name_ files, the updated list (based on #149) is a bit harder to see. I'll add the _relative path) besides the filename, just like the `Search` Side Bar.

Hope this helps
