### ISSUE TITLE
bookmarks.json missing

### ISSUE THREAD

**Issue by ba-2** [alefragnani/vscode-bookmarks#237]
Hi,

I couldn't find bookmarks.json either in my roaming directory or in my workspace directory.

I'm using VSCode in Windows, and have a workspace with multi-root folders.

Please let me know where my bookmarks.json is stored.

**Comment by alefragnani** [comment]
Hi @ba-2 ,

The `bookmarks.json` is available only if you use `saveBookmarksInProject` as `true`. It will be saved inside the `.vscode`, in the root directory.  Otherwise it is saved in VS Code internals (used to be in Chromium/LocalStorage, and I think now is in `AppData\Roaming\Code\User\workspaceStorage\xxxx\state.vscdb`, but I'm not sure). 

But, if you have a _multi-root_ project, this setting is not supported, yet, so it will _always_ be saved in VS Code internals.

Hope this helps

**Comment by ba-2** [comment]
Thanks Alessandro. I moved some files between folders and I find the bookmarks I saved before the move missing. I thought I'll modify the path in the bookmarks.json if I could find where it is located.

I tried checking the VSCode internals Local Storage, and I couldn't find any files listed there.

**Comment by ba-2** [comment]
Thanks. I'll give that a try.

**Comment by alefragnani** [comment]
Unfortunately not. There is no command for that. 

The Bookmarks are stored separately for each _workspace_ by VS Code, and one can’t access the other.

There is an open issue #287 , asking for a _global_ approach for bookmarks, which could partially fit your need. Why partially? Because you pointed out _remote projects_, and I have the feeling that remotes wouldn’t be supported, specially because the connection would depend on the _remote extension/protocol_ itself, not the Bookmarks extension.

If #287 is what you are looking for, please upvote the issue, so I’m able to see how required the feature is.

Hope this helps

**Comment by ivangretsky** [comment]
I like that idea! But it will be another option, not a replacement for current mechanism. So the data buried in VS Code internals kind of still worries me. Will it stay there forever? Or maybe I should just forget about it)

**Comment by alefragnani** [comment]
Yes, an option, not a replacement mechanism.

Out of curiosity, why are you worried about the data? Performance concerns, security concerns? Other concerns?

**Comment by ivangretsky** [comment]
> Out of curiosity, why are you worried about the data? Performance concerns, security concerns? Other concerns?

I guess all of that. But most of all is having something beyond  my control)

**Comment by alefragnani** [comment]
Well, the way the Bookmarks extension stores its data/state is the same way not only other extensions do that, but VS Code itself. In fact, is the way VS Code proposes to do, via its APIs. In the end, if you have concerns about that, you may have concerns with VS Code itself too.

Maybe, in this case, you should use the [Portable Mode](https://code.visualstudio.com/docs/editor/portable). Every VS Code data will be under your control. But yet, separated on each workspace, as every other extension that stores info about the workspace.

Also, VS Code internals are SQLite databases so, you could create a shell script and clear every workspace once, and switch the extension settings to store bookmarks in workspace. Then, the bookmarks will be under your control in the workspace. 

Another alternative would be not store bookmarks between sessions, so whenever you close VS Code, the bookmarks are gone. If that's a solution for you, feel free to open a new issue requesting that.

Hope this helps.
