### ISSUE TITLE
Is there any way to bookmark w/ mouse on the gutter (like breakpoints)?

### ISSUE THREAD

**Issue by sarbbottam** [alefragnani/vscode-bookmarks#24]
Is there any way to bookmark w/ mouse?

**Comment by alefragnani** [comment]
I don't remember seeing an API for that, but worth investigate :+1:

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/5455

**Comment by Bill-Stewart** [comment]
Right-click and choose `Bookmarks: Toggle` menu option?

**Comment by alefragnani** [comment]
@Bill-Stewart you also have this option, but this issue is related to _click on the gutter_, just like _breakpoints_. I updated the title to reflect that, thanks 👍

**Comment by ewwink** [comment]
please add right click `Bookmarks: Jump to Next` and  `Bookmarks: Jump to Previous`

thanks

**Comment by alefragnani** [comment]
Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. But this "re-focus" will be based on community feedback/support.

I'm closing this issue because the VS Code issue that it depends on, has no update from VS Code team members for more than two years. It is planned on "Backlog" Milestone, so it appear it will not be released soon. I'm subscribed to that issue, so if/when it is closed, I'll be notified.

@ewwink I created #150 to track your request 👍

**Comment by ewwink** [comment]
@alefragnani OK, thanks.

**Comment by poucz** [comment]
Regarding [https://github.com/microsoft/vscode/issues/5455](https://github.com/microsoft/vscode/issues/5455) I think that VS Code made change in API

**Comment by alefragnani** [comment]
Hi @poucz ,

Kind of, but not exactly the same as bookmarks.

Instead, they added a _context menu_ approach, and the extension was updated to support this in #615 , released around two years ago.

Enjoy 😬
