### ISSUE TITLE
On Toggling the Bookmark in VSCode it adds a character in file

### ISSUE THREAD

**Issue by EagleHawk** [alefragnani/vscode-bookmarks#240]
After toggling a bookmark on a line the extension adds a character to a file. Thus causing error in lint and while executing the code.

Like as below:
̥̥̥

**Comment by thorn0** [comment]
Do you toggle it using the keyboard? Are you on Windows?

Then most probably the cause is here: https://github.com/microsoft/vscode/issues/81268

If your system keyboard layout has Alt-mappings, then Ctrl+Alt-shortcuts mapped to the same letters won't work anymore in VS Code. :( E.g. I have Alt+L=Ł in my layout, so Ctrl+Alt+L shortcut of this extension stopped working for me, and the VS Code team can't fix this (see the issue above).

**Comment by alefragnani** [comment]
Thank you @thorn0, I guess that too. 

@EagleHawk the extension does not edit the text, no matter how you toggle the bookmark (keyboard shortcut or command palette).

I suggest you change the keyboard shortcut to something other than `Ctrl + Alt` combination, to avoid future issues.

Hope this helps
