### ISSUE TITLE
Idea: Bookmark on find

### ISSUE THREAD

**Issue by luca1010** [alefragnani/vscode-bookmarks#252]
Hi, It would be great to mimic Notepad++ "bookmark lines" functions.
When I use the "Find" function in N++ I can check the "bookmark line" option that automatically sets a bookmark on all lines that match the find.

I could not find this in this extension and I think it would be extremely useful.

**Comment by alefragnani** [comment]
Hi @luca1010 ,

I didn’t use Notepad++ that much, so I’m not sure about this specific feature. 

But, if you are talking about bookmarking results from **Find in Files**, there was an issue back in 2015 (#7), but it was closed because the VSCode team didn’t provide proper API for that.

On the other hand, if you are talking about bookmarking results from **Find** command (inside a file), it is already being tracked in #77.

Hope this helps
