### ISSUE TITLE
Refreshing bookmarked text erroring out.

### ISSUE THREAD

**Issue by shawinder** [alefragnani/vscode-bookmarks#253]
I am getting following error when I try to use refresh context menu the text in `bookmark explorer`

```
Error running command extension.refreshObjectExplorerNode: command 'extension.refreshObjectExplorerNode' not found. This is likely caused by the extension that contributes extension.refreshObjectExplorerNode.
```

![image](https://user-images.githubusercontent.com/2242439/68966548-448e8800-0793-11ea-8f60-f51220c48caa.png)

**Comment by alefragnani** [comment]
Hi @shawinder ,

Weird, I’m not aware of this command 😕 ... 

The Bookmarks Side Bar does not have a _context menu_ item called `Refresh`, but instead a button in its _Title_. Also, the Bookmarks extension does not contribute with any command called `extension.xxx`, neither `xxx.refreshObjectExplorerNode`, so I’m not sure _how_ it failed.

Are you sure you have my Bookmarks extension installed, instead of a similar?

Hope this helps.

**Comment by shawinder** [comment]
Hi @alefragnani . Thanks for the clarification. You are right. I am no longer seeing the `refresh` option and strangely enough now the only context menu items I see are either `edit label` or `delete`. I am going to close this as it's a non-issue.
