### ISSUE TITLE
Keyboard shortcuts interfered by windows ones

### ISSUE THREAD

**Issue by Rab815** [alefragnani/vscode-bookmarks#259]
I loaded this extension in VSCode and the toggle bookmark on and off short cut is fine but the ctrl + alt + L wants to lock my computer and the ctrl + alt + j doesn't seem to respond instead it wants to open the live share functionality.  I have to use the bookmark explorer to navigate between them.  Can these shortcuts be altered?

**Comment by alefragnani** [comment]
Hi @Rab815 ,

Sure you can customise _any_ shortcut. You just have to follow [these instructions](https://code.visualstudio.com/docs/getstarted/keybindings) from VS Code documentation.

If you are having conflict with `Ctrl + Alt + L`, you may be using Linux, right? I don't use linux, so I didn't know about this shortcut when I decided to use it. And about `Ctrl + Alt + J`, its the Live Share extension which is conflicting to Bookmarks, because my extension is _older_ :grind
