### ISSUE TITLE
Avoid Bookmarks from being toggled in the new Search Editor

### ISSUE THREAD

**Issue by pharapiak** [alefragnani/vscode-bookmarks#279]
With the long awaited "Open in editor" feature now here, it is possible to drop a bookmark on any of the lines that appear in that editor. That seemed very promising, perhaps even a way to implement your [issue 7](https://github.com/alefragnani/vscode-bookmarks/issues/7).  

The problem is, the bookmarks are are not stored anywhere, and don't appear in the Bookmarks Explorer.

So this is partly a bug report and a partly a feature request: bookmarks shouldn't be allowed in the Search result editor if they don't really work... but it sure would be nice if bookmarks placed there were kept as bookmarks on the file that the bookmarked line was found it.
![Capture](https://user-images.githubusercontent.com/6496259/78383296-255b9000-75a6-11ea-9a20-99a3ff15ef28.PNG)

**Comment by alefragnani** [comment]
Hi @pharapiak ,

I don't use/like this view, so that may be the reason I didn't get this issue before. And running the command, raises an error for me: `Unable to open '': resource is not available.` 

But you described an interesting scenario, and opinions may differ on _What to do with the Bookmark_?

Yes, it could be a way to implement #7, and I would say a bit more: _Wouldn't be cool to bookmark the line in the Search View and the bookmark be added to the referred file/location as well?_ I think 😄 

At first, I would handle this as a bug report, and the fix would be _block bookmarks from being toggled in this view_. That other idea, would be handled in another issue.

Hope this helps

**Comment by pharapiak** [comment]
Yes, I agree.
