### ISSUE TITLE
Bookmarks not visible any more

### ISSUE THREAD

**Issue by aybiss** [alefragnani/vscode-bookmarks#280]
Until a recent update of VSCode, bookmarks were visible in the left margin next to the code. Now they are not showing. The bookmarks can be created just fine and I can navigate to them, I just can't see them.

VSCode 1.43.2
Bookmarks 11.0.0
Using remote SSH

Is this a known problem or is it something I have done to my editor settings or something else?

Thanks in advance, your extension is invaluable.

**Comment by alefragnani** [comment]
Hi @aybiss ,

First of all, thank you for your kind words. I'm glad to know the extension is being useful.

I have received a few reports (#34, #43, #160, #170, #272) about missing Icon (Side Bar) and it was always related to some error while installing/upgrading VS Code or the extension.The bookmark icon, on the other hand, I just remember on issue, caused by the fact of using a Retina display (Mac) when the extension was still using PNG images. When I upgraded to SVG the problem disappeared.

You said a recent VS Code update has happened, so I guess it _could be_ the reason. Try to reinstalling the extension, so see if it works. It must be a full reinstall, which means:

1. Uninstall the extension 
2. Close all VS Code instances (reload window is not an option)
3. Open VS Code
4. Install the extension again

It's very important to _close all VS Code instances_, because VS Code removes the extension (old/uninstalled) when it starts from zero.

Hope this helps.

**Comment by aybiss** [comment]
Thanks very much for the comprehensive reply. When loading up vscode this
morning fresh it was working fine. If they disappear again I will try your
suggestions. Have a great weekend!

**Comment by alefragnani** [comment]
Thank you! That's great to hear 🎉 

Enjoy...

**Comment by jvzr** [comment]
If somebody is in the same situation, and a VSCode restart didn't fix it, just make sure the 'glyph margin' is enabled: `"editor.glyphMargin": true`

It's not on by default, somehow, and I've spent more time "debugging" the icon missing than I'd like to admit...

**Comment by alefragnani** [comment]
Hi @jvzr ,

Thank you for the tip!

Maybe something has changed in newer VS Code releases, because for me, the `editor.glyphMargin` default value is `true`.

**Comment by jvzr** [comment]
Must have been an issue on my end, because as you made me double-check it reverted to on by default.

Longer story: your reply made me double-check, so I opened Settings. Next to the glyph margin setting, which was enabled, it displayed the blue indicator meaning this is not the default. I clicked once, the value set to disabled but the indicator remained. I clicked again, the value set to enabled and the indicator disappeared. I must be crazy.

In any case, it might be useful to let users know that this setting must be enabled for the gutter icon to show. People like me who had it disabled before because they had no use for it until now might appreciate the info 😄 I blame the name of the setting, as I was looking for something something "gutter" and only by trial and error found the misnomer.

**Comment by alefragnani** [comment]
> In any case, it might be useful to let users know that this setting must be enabled for the gutter icon to show.

That's a good idea, thanks!

In fact, I didn't know about that VS Code setting, until now 😁

**Comment by farukonfly** [comment]
> Hi @aybiss ,
> 
> First of all, thank you for your kind words. I'm glad to know the extension is being useful.
> 
> I have received a few reports (#34, #43, #160, #170, #272) about missing Icon (Side Bar) and it was always related to some error while installing/upgrading VS Code or the extension.The bookmark icon, on the other hand, I just remember on issue, caused by the fact of using a Retina display (Mac) when the extension was still using PNG images. When I upgraded to SVG the problem disappeared.
> 
> You said a recent VS Code update has happened, so I guess it _could be_ the reason. Try to reinstalling the extension, so see if it works. It must be a full reinstall, which means:
> 
> 1. Uninstall the extension
> 2. Close all VS Code instances (reload window is not an option)
> 3. Open VS Code
> 4. Install the extension again
> 
> It's very important to _close all VS Code instances_, because VS Code removes the extension (old/uninstalled) when it starts from zero.
> 
> Hope this helps.

I did that, but it still doesn't work

**Comment by Steviey** [comment]
+1
