### ISSUE TITLE
Syncing bookmarks between duplicate workspaces

### ISSUE THREAD

**Issue by vassyz** [alefragnani/vscode-bookmarks#292]
When using two identical workspaces with "Duplicate Workspace in New Window",
when I add a bookmark in one workspace the bookmarks don't update in the other workspace,  although I can see the JSON file updating. I unsuccessfully tried clicking the "Refresh" icon (don't really know what that does). I also tried with "Save Bookmarks In Project" on and off. The only way I can get it to work is to restart the VS Code window.

Is this a bug or am I doing something wrong?

**Comment by alefragnani** [comment]
Hi @vassyz ,

It appears you aren’t doing anything wrong, neither is a bug.

I didn’t even know about this new command, but searching references about it, it appears _it doesn’t really duplicates the current workspace_ but instead _open a new window with the same set of folders_. Which in the end men’s, its _a new_ workspace. At least it is how I understand from [this command](https://github.com/Microsoft/vscode/issues/65169#issuecomment-447732533) in  https://github.com/Microsoft/vscode/issues/65169.

Another reason to think this is how it works, is because when you run the command, the new window has an “untitled workspace name”, instead of the the same name from the original workspace. So, you end up with “another workspace”.

If that’s the case, the bookmarks won’t be synced. When the bookmarks are saved, they are relative to the Folder/Workspace, so each one will have its own set of bookmarks. The `saveBookmarksInProject` setting on other hand, won’t work for you either, because it is not supported on Workspaces (more details [in this comment](https://github.com/alefragnani/vscode-bookmarks/issues/82#issuecomment-343691392)). The issue #193 tracks the update to support that.

Hope this helps

**Comment by vassyz** [comment]
@alefragnani thank you for your detailed answer. I will try to change my workflow to adapt to the technical limitations. My biggest issue now is that it's confusing what bookmarks are in which workspace. I will uncheck `saveBookmarksInProject` and use bookmarks just in one workspace.

**Comment by alefragnani** [comment]
No problem! I always try to help users as much as possible.

I suggest you to turn off `saveBookmarksInProject` for this case, and stay tuned for the proper release of multiple window support (https://github.com/Microsoft/vscode/issues/43188). When it happens, I’ll still need to update the extension to support sync (watch and update bookmarks from the other window ).
