### ISSUE TITLE
allow bookmarks creation in Jupyter files (.ipynb)

### ISSUE THREAD

**Issue by JoopBanaan** [alefragnani/vscode-bookmarks#294]
I like to create bookmarks as well in Jupyter files (extension .ipynb)
Currently  (version 11.1) I get a pop up "open a file first to toggle bookmarks"

**Comment by alefragnani** [comment]
Hi @JoopBanaan ,

I’m not aware about how Jupyter Notebooks works, but looking at VS Code announcement (https://code.visualstudio.com/docs/python/jupyter-support) and looking it open issues in VS Code repository, it seems to be a WebView with some pieces of editable source code, so I guess you are trying to add bookmarks in that editable source code, right?

If that’s the case, I guess this issue recently opened in VS Code repository may be the reason  (https://github.com/microsoft/vscode/issues/96532). BTW, the Notebook API is still in early stages (https://github.com/microsoft/vscode/issues/93265  api-proposal to be precise), so it would take some time (at least May, based on the milestone attached to the issue) to have something to work with.

I just wonder how each `ActiveTextEditor` will be _announced_ for extensions, because today, each one refers to _one file in file system_, and with Jupyter Notebook, it could end up with _many_ `ActiveTextEditor` referring to the same file in file system.

So, I need to help at least until May/June, after the oficial API is released, to take a look at this.

Hope this helps

**Comment by alefragnani** [comment]
I’m closing as duplicate of #531
