### ISSUE TITLE
Toggle Editing Mode

### ISSUE THREAD

**Issue by muellerkyle** [alefragnani/vscode-bookmarks#30]
Would it be possible to add the capability to place the opened file into edit mode when a bookmark is added?

To be more clear:
1. Open a project with multiple files.
2. Click on a file and add a bookmark without making any other edits. The file will be listed with the file name in italics
3. Click on another file
4. The file gets closed (yet the bookmark does persist)

Could we have the option so that the file is placed into edit mode and does not get closed when a bookmark is added?

**Comment by alefragnani** [comment]
Hi @muellerkyle ,

I get it :+1:  I don't know if there is an API for that, but I will take a look. If yes, I could add a `config` for that.

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/10568

**Comment by muellerkyle** [comment]
Somehow I missed responding to your update. Apologies for that! 

I see the ticket that you opened with vscode. It may be of interest to note that I originally logged this as a requested feature with the vscode team and was directed to see if I could get you to implement it.

This seems to be stuck in a loop. See Tyriar's response below mine.

See: https://github.com/Microsoft/vscode/issues/224#issuecomment-218665430

**Comment by alefragnani** [comment]
Hi @muellerkyle, no problem about that 👍 

I understand you concern, but I don't see a _loop_ here. My issue to _force a document to be pinned_ is still open. 

Tyriar's suggested to you to open an issue here because, since this extension is not a _core extension_, he could not be responsible to update the extension (unless of course via PR, which would be wellcome 😄 ). But in fact, the issue is a bit different. We don't want to _make openned files to be automatically pinned_, but in fact, _pin an already openned document_.

So, we still have to wait. Unfortunatelly there is no _milestone_ assigned.

Maybe you could turn off _preview tabs_ (`"workbench.editor.enablePreview": false)` in the meantime.

**Comment by muellerkyle** [comment]
Hi alefragnani,

There seems to have been some progress on this item on the VS Code repo.

Any chance that you could add this after the next drop from their side?

Thank you!

**Comment by alefragnani** [comment]
Hi @muellerkyle , that's the idea 😄

**Comment by muellerkyle** [comment]
Thanks @alefragnani !

**Comment by muellerkyle** [comment]
Hi alefragnani,

I have come back around to VS Code and noticed that you got this fix in, but issue # 74 seems to have broken the fix.

I checked the API for VS Code and I think that there is a workable compromise that keeps the fix for issue #74 in tact.

I've cloned your repo and will put in a pull request so that you can see the change.

Thank you!

**Comment by alefragnani** [comment]
Hi @muellerkyle ,

If probably happened caused by a VS Code API change, reverting the `preview` default value, because when I updated the code, I'm pretty sure it worked just fine. I even [commented that](https://github.com/alefragnani/vscode-bookmarks/issues/74#issuecomment-309223651) 😄 .

Anyway, I will take at your PR and see how it goes. If everything is fine, I will push an update next weekend.

Hope this helps

**Comment by muellerkyle** [comment]
Thanks Alessandro. 

I appreciate the consideration!
