### ISSUE TITLE
Bookmarks set with repository gets lost when using checkout between branches

### ISSUE THREAD

**Issue by weidmaster** [alefragnani/vscode-bookmarks#303]
I set bookmarks inside functions from legacy codes that have actions in if blocks and it works really well, but unfortunatelly when using checkout between branches the bookmarks get all lost.

The ideal solution would be to return the bookmarks that were set in a specific branch when checked out.

**Comment by alefragnani** [comment]
Hi @weidmaster ,

It seems you are asking the same as #298, which was closed in favor of #177, (a broader idea).

As an alternative (also suggested in #298), if you don’t use Workspaces (multi-root folders) you could save the bookmarks in the project, using the `"bookmarks.saveBookmarksInProject“` setting, and commit the `.vscode/bookmarks.json` file in the repo. So, when you checkout a branch, it restore its bookmarks. Doing so, each branch will have its own bookmarks.

Otherwise, please upvote #177.

Hope this helps

**Comment by weidmaster** [comment]
> Hi @weidmaster ,
> 
> It seems you are asking the same as #298, which was closed in favor of #177, (a broader idea).
> 
> As an alternative (also suggested in #298), if you don’t use Workspaces (multi-root folders) you could save the bookmarks in the project, using the `"bookmarks.saveBookmarksInProject“` setting, and commit the `.vscode/bookmarks.json` file in the repo. So, when you checkout a branch, it restore its bookmarks. Doing so, each branch will have its own bookmarks.
> 
> Otherwise, please upvote #177.
> 
> Hope this helps

Indeed I don't use workspaces, didn't get to the point where I need to for the moment. I upvoted #177 but it seems it is a big challenge for you guys. I will try to commit the file mentioned, but I just need the extension to work in my copy of the repository, therefore no need to commit to the repository itself. The use is very simple, the bookmark should only be attached to the HEAD branch I think. I can see now why it is a challenge, as checking out branches do indeed change the files in the working directory and other people would like the bookmarks to reflect it.

Thanks for your time to reply and I hope development go smooth for you guys. Best regards.
