### ISSUE TITLE
Key binding for edit label gives error

### ISSUE THREAD

**Issue by jd-0001** [alefragnani/vscode-bookmarks#308]
I have bound key to edit labels:

```js
{
  "key": "alt+b e",
  "command": "bookmarks.editLabel"
}
```

But when I run it to edit label it gives:
```
Running the contributed command: 'bookmarks.editLabel' failed.
```

:thinking:

**Comment by alefragnani** [comment]
Hi @jd-0001 ,

This command is not “customizable” because it is intended to be used only by the Side Bar, when you select the bookmark to edit the label. A similar issue was reported sometime ago #214, and as described in [this comment](https://github.com/alefragnani/vscode-bookmarks/issues/214#issuecomment-638764280)

> If you want update the bookmark’s label, via Keyboard Shortcuts, you should use the Bookmarks: Toggle Labeled command. It will open the same input for you to define/update the label assigned to the Bookmark in the current line.

I created a new issue (#306) to “hide” this commands from being customizable, and avoid confusions. It’s coming in the next release

Hope this helps
