### ISSUE TITLE
Not available on VSCodium

### ISSUE THREAD

**Issue by eloudsa** [alefragnani/vscode-bookmarks#317]
Hi.
I just installed VSCodium and I noticed that "Bookmarks" is not available as extension.

Any idea why the extension is not visible through VSCodium?

Thanks

**Comment by alefragnani** [comment]
Hi @eloudsa ,

It’s not available because I’m not publishing the extension on `open-vsx` (which I discovered the existence about a month ago). 

In fact, I’m just publishing on MS Marketplace, and there is another issue open #260 asking to release `.vsix` files using GitHub releases, so it could be available for VS Code _alternatives_.

Hope this helps
