### ISSUE TITLE
[FEATURE] - Support clear the bookmark label in `Toggle Labeled` and `Edit Label` commands

### ISSUE THREAD

**Issue by cateyes99** [alefragnani/vscode-bookmarks#320]
This command should give the capability to remove the label given to a labeled bookmark. Currently it isn't actually about the functionality of `Toggling` a label given to a bookmark. Rather it's about `adding` & `editing` a label.

**Comment by alefragnani** [comment]
Hi @cateyes99 ,

Yes, that's the expected behaviour. The `Toggle Labeled` command will create and update the label, not remove it. If you want to _remove_ a bookmark, labeled or not, you should use the `Toggle Bookmark` command.

I understand your point, and I think an improvement could be made on that InputBox. I could add a `clear` button, remove the label and turn it a regular bookmark.

Hope this helps

**Comment by cateyes99** [comment]
I know that the `Toggle Bookmark` command remove a bookmark. What i want is removing|clear the label but keeping the bookmark itself. 😄
