### ISSUE TITLE
jump to bookmark

### ISSUE THREAD

**Issue by gaiahub** [alefragnani/vscode-bookmarks#329]
The instructions for adding: `Ctrl + Shift + 2` then `Ctrl + 2` to jump to bookmark does not work.

**Comment by alefragnani** [comment]
Hi @gaiahub ,

I think you installed (or is reporting) the wrong extension. This extension toggles unlimited number of bookmarks and has two different commands to jump (`Jump to Next` and `Jump to Previous`).

My other extension [Numbered Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.numbered-bookmarks) is the one which uses `Ctrl + Shift + #` to add and `Ctrl +#` to jump.

Which one are you talking about?

**Comment by gaiahub** [comment]
I am on 
![image](https://user-images.githubusercontent.com/49032945/91494312-7ded3b80-e86d-11ea-915f-cc55474e211f.png)

I added the bookmark but when i try to jump to it, the `ctrl+#` does nothing.

**Comment by alefragnani** [comment]
You are reporting on the right extension, but using the commands from the other extension.

This extension doesn't have a `Jump to bookmark` command, but instead `Jump to Next` and `Jump to Previous`. So, you won't be able to jump to specific bookmarks. Also, the default shortcuts are `Ctrl + Alt + K` to `Toggle Bookmark` and `Ctrl + Alt + J` and `Ctrl + Alt + L` to `Jump to Previous` and `Jump to Next` bookmarks, respectively. If you changed the shortcuts and they aren't working, I suggest you to check for conflicts in VS Code. Just open the `Keyboard Shortcuts` UI and type `Ctrl + #` and see the commands that has the same shortcut.

Otherwise, if you want/need to jump to specific bookmarks, you should use my other **Numbered Bookmarks** extension.

Hope this helps

**Comment by gaiahub** [comment]
thank you,  i didnt see `Ctrl + Alt + J` anywhere.

**Comment by alefragnani** [comment]
That's great 🎉

Enjoy

**Comment by natgross** [comment]
Can I use both extensions, numbered bookmarks & this one here, simultaneously without problems?

**Comment by alefragnani** [comment]
Hi @natgross ,

Sure! I do that myself on both computers I use. 

There is no _conflict_, unless you add both bookmarks on the same line, you won't see the icons properly. But that's a VSCode issue, which also happens with Breakpoints.

Hope this helps
