### ISSUE TITLE
Bookmarks aren't moving when editing

### ISSUE THREAD

**Issue by CoreyVidal** [alefragnani/vscode-bookmarks#333]
Basically, after I set a bookmark, if I enter new lines in my document, all the bookmarks stay where they were, and get offset.

Version: 1.49.0 (user setup)  
Electron: 9.2.1  
Chrome: 83.0.4103.122  
Node.js: 12.14.1  
V8: 8.3.110.13-electron.0  
OS: Windows\_NT x64 10.0.19041

I'm running the latest version of Windows 10 (2004), and freshly reinstalled my OS / entire computer just a few days ago.

I installed the extension via the Extensions built into Visual Studio Code.

Let me know how you'd like me to provide info.

**Comment by alefragnani** [comment]
Hi @CoreyVidal ,

The bookmarks should move, if you add or delete lines above them. Unless you define the `bookmarks.useWorkaroundForFormatters` setting to `true`, which (as the name describes) is a _workaround_ for users that uses formatters like Prettier (still have to update the extension to support such tools). But it doesn't appear to be your scenario, because you said you are using a clean install.

Are you using any formatter/linter extension? Does it happen on any kind of file?

You could open the `Developer Tools` and take a look at `Console` for errors. Maybe something is happening.

Hope this helps

**Comment by CoreyVidal** [comment]
Ahhhh, I do use a formatter, but I don't have it run automatically when I save. I had set it to "true" which was wrong of me. Thanks for the help!

**Comment by alefragnani** [comment]
No problem!

This is definitely something that I need to revisit, and deliver proper support.

Thank you
