### ISSUE TITLE
After update no gutter icon mark 

### ISSUE THREAD

**Issue by crystalfp** [alefragnani/vscode-bookmarks#340]
Issue Type: <b>Bug</b>

After last extension update, no icon appears next to the marked line. With Ctrl-F2 the bookmark is created and appears in the sidebar, I can go to it with F2, but no icon appear in the gutter.

Here are my extension settings:
![image](https://user-images.githubusercontent.com/865866/96667036-8d15d480-1358-11eb-9433-cc230c624faa.png)

Thanks for looking!
mario

Extension version: 11.4.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (20.65GB free)|
|Process Argv|D:\Montessori\Libro - Tecnologia in famiglia\Tecnologia in famiglia.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alefragnani** [comment]
Hi @crystalfp ,

I have seen some issues after extensions being updated (not only mine), and sometimes, the only way to fix it was uninstalling and installing it again (with a full VS Code quit, so VS Code actually deletes the extension from your system).  But most of the times, it was related to the Side Bar icon, not from the gutter.

Just recently, a similar issue appeared (#280), and it was caused by a VS Code setting called `editor.glyphMargin`. Somehow,  it was defined as `false` on user's installation.

You could try both ideas, to see if it works.

Hope this helps

**Comment by crystalfp** [comment]
Yes, was `glyphMargin` set to false the culprit. Setting it true and the bookmarks reappear.
Maybe during installation/update it could be forced to true.
Thanks!
mario
