### ISSUE TITLE
Sticky Bookmarks fail with trimAutoWhitespace set to True

### ISSUE THREAD

**Issue by jing2si** [alefragnani/vscode-bookmarks#35]
I config in 'settings.json' as follow:

```
"bookmarks.useStickyBookmarks": true
```

When i add some new blank line before the bookmark, the bookmarks can not stick

**Comment by jing2si** [comment]
as follow is my test code,
when i add new line in 'o' object,the bookmark can not stick
```javascript
var o = {}
function test() {}
```

**Comment by alefragnani** [comment]
Hi @jing2si ,

Sorry, but I couldn't reproduce your problem 😞 . Take a look at the gif below. I used with and without indent and in both cases, the bookmark is correctly moved with the code. 

![35](https://cloud.githubusercontent.com/assets/3781424/18650518/de3c14ec-7e9b-11e6-885a-946a4fd270c5.gif)

I also tried with an empty line between them, no problem.

Are these scenarios covering your usage? Do you have any more info to share?

**Comment by jing2si** [comment]
need more empty line.
before the empty line must have **indent**.
![1](https://cloud.githubusercontent.com/assets/2288824/18655050/34da61e2-7f18-11e6-82b8-b700ff8bb26d.gif)

**Comment by alefragnani** [comment]
Hm... I knew this wasn't strange to me...

This error was introduced by an update in VS Code (don't remember exactly when). I thought I had fixed but instead I just _turned off_ 😢 . That update introduced a new setting `editor.trimAutoWhitespace`, that you must set to `false` in order to temporarily fix this.

Hope this helps.
