### ISSUE TITLE
[QUESTION] - What does indent mean in marklist

### ISSUE THREAD

**Issue by bugknightyyp** [alefragnani/vscode-bookmarks#350]
<img width="447" alt="vscode-bookmarks-indent" src="https://user-images.githubusercontent.com/2301065/98582736-53ecd680-22fe-11eb-9cb4-15f2130f32b2.png">

**Comment by alefragnani** [comment]
Hi @bugknightyyp ,

It doesn’t mean anything, except the _first char_ (probably a `Tab` because the Bookmark is at `Col 2`) from your source 😄 .

It shouldn’t be there, because when you toggle a bookmark, the Side Bar displays a _trimmed_ version of the bookmarked line, but as reported in #344 and #348 , you have two scenarios where this `trim` where not being applied. You probably faced one of these two scenarios, right?

If that’s the case, both issues will be fixed on the next release.

Hope this helps

**Comment by bugknightyyp** [comment]
@alefragnani Thank you for your kind reply.
