### ISSUE TITLE
[FEATURE] - Making Bookmarks available in all Workspace

### ISSUE THREAD

**Issue by franklinkf** [alefragnani/vscode-bookmarks#353]
I am using this feature extensively. My main issue is that the bookmarks defined in one workspace is not available in another workspace.  If I duplicate the workspace also, I am not getting the bookmarks in the duplicate window.  I always work in VS Code opening multiple workspaces.   Is this feature already exists? Am I missing something? Else, please consider this request.

Thank you for a fantastic feature

**Comment by alefragnani** [comment]
Hi @franklinkf ,

Thank you for your kind words. I’m glad to know you like the extension.

About your request, maybe you are asking something similar to #287 , when bookmarks end up available no matter which Workspace or Folder you opened. It would be considered a _global resource_.

There is also another open issue #193 , which makes the `saveBookmarksainProject` setting to work while you use Workspaces (multi-root). 

Which one better fit your scenario, if any?

The reason why the extension has the current approach is because VS Code itself delivers _per session_ storage, and each folder or workspace you open, is a different session. So, when you open the same file, from two different _sessions_ it is considered _a different file_.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question, and the feature requested is already reported on other issues (duplicate)

**Comment by vassyz** [comment]
Sorry, I know this issue is closed. But will syncing bookmarks on duplicate workspaces never be available because of how the session works?

**Comment by alefragnani** [comment]
Hi @vassyz ,

With #287 , no matter in which workspace you open a file, its bookmarks should be available. This will happened because the idea is to store the _complete file path_ for each file, instead of the _relative to the workspace_ approach that exists today. I think it would work just fine, but I tend to believe that _remotes_ won't work, but without proper testing, I can't say for sure.

Syncing, may be a bit tricky. If I understand correctly, you want not only that a bookmark is available in any workspace that contains that specific file, but also that, when you add a bookmark in one workspace it should _automagically_ appear in the other workspaces where that file is. If that's the case, the extension itself must change to _recognize external changes to the bookmarks data_, which is not supported today. If this is your expectation, feel free to open a new issue, so I could keep track of it independently.

Hope this helps

**Comment by vassyz** [comment]
Hi @alefragnani 

Thank you for your reply. I'm not sure if a new ticket is needed, because it's exactly the issue @franklinkf describes here.

This will mostly be an annoyance for people using multiple monitors/desktops.
When you run `Duplicate Workspace in New Window` to get two workspaces (for two monitors) the duplication creates a new `Untitled` workspace. When duplicating, the bookmarks sync, but when adding a bookmark in Workspace 1, the Workspace 2 doesn't get updated. So this makes it a lot less useful for people like me because you forget which monitor has which bookmark.

I'm not even sure if this is technically possible to implement.
