### ISSUE TITLE
Set the centering point

### ISSUE THREAD

**Issue by Torguen** [alefragnani/vscode-bookmarks#361]
Hello, is it possible to configure the point where the vertical scroll is located when I select a bookmark?
Currently the point is in the center of the screen, I would like to move it further up, how can I do this?

**Comment by alefragnani** [comment]
Hi @Torguen ,

No, you can't configure. It will always be _centered_.

On the other hand, the VS Code API also supports a _at top_ position, as you can see here https://code.visualstudio.com/api/references/vscode-api#TextEditorRevealType. I'm not sure how it will be behave (will it have an offset, for instance?), but based on the others `InCenter` I use today, I guess it will be just fine.

Otherwise, if your idea is _move a bit up_ the position, and not exactly _at the top of the window_, so it wouldn't be possible.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.
