### ISSUE TITLE
Suggestion: "Go to next/previous bookmark and select" command

### ISSUE THREAD

**Issue by Bill-Stewart** [alefragnani/vscode-bookmarks#37]
Currently we cannot select when moving between bookmarks. This suggestion is to add commands to select while jumping to next/previous bookmark in the current file.

**Comment by alefragnani** [comment]
Hi @Bill-Stewart ,

When you say _select_ do you mean _select the contents of bookmarked lines_?

**Comment by Bill-Stewart** [comment]
Correct. Suppose you put bookmark on line 5 and set bookmark. Then I select line 10. If I jump to bookmark, my selection disappears. This suggestion is to select or extend selection to bookmarked line when repositioning cursor.

**Comment by alefragnani** [comment]
Well, I don't see a problem to _loose the selection_ when you _jump to bookmark_, because in fact, you are moving the cursor to the new place. It's just like a **Go to line** or **Mouse Click**. At least it is the same behavior as others editors that I have used.

But, I think I could _restore the selection_ when you use **Bookmarks: List** and **Bookmarks: List from All Files** and _cancel_ the navigation. Today, it only returns the cursor to the line where it was, but not the selection.

What do you think?

**Comment by Bill-Stewart** [comment]
Here is an example use case:

1. Bookmark two separate lines
2. Jump to first bookmark
3. (new command) Jump to next bookmark + select

Result would be that first bookmarked line through second bookmarked line would be selected.

In other words this could be a way to select a range of bookmarked lines without holding the <kbd>shift</kbd> key or using the mouse.

**Comment by alefragnani** [comment]
Hi @Bill-Stewart , what do you think to be the best scenario? _Just select_ to the next/previous bookmarked line, or _extend the selection_?

**Comment by Bill-Stewart** [comment]
If selection exists, then extend to bookmark. If no selection exists, create new selection from cursor position to bookmark.
