### ISSUE TITLE
Sticky Bookmarks fail if file has unstaged changes in git and already bookmarked when opened

### ISSUE THREAD

**Issue by duanehutchins** [alefragnani/vscode-bookmarks#40]
To reproduce this issue, 
1. Enable bookmarks.useStickyBookmarks = true (I also have "editor.trimAutoWhitespace": false, but the bug persists with or without it)
2. Create a file and add it into git so that it's tracked.
3. Open the file in vscode and change it. Save the changes but don't stage the changes in git.
4. Add a bookmark on the file.
5. Close the file and then open it again.
6. Make a change to the file above the line that's bookmarked.  The bookmark moves or fails.

Here's a gif of the bug in action.  Note the lines indicating that the file is currently versioned and changed in git. 

The bookmark works at first; it only fails after closing the file and reopening it:
![vscodebookmarkissue](https://cloud.githubusercontent.com/assets/1530028/19560799/db46cc4e-96a3-11e6-9198-86b8da2f531e.gif)

**Comment by alefragnani** [comment]
Hi @duanehutchins ,

I'm sorry taking so long to answer. I saw your post but forgot to give the proper attention because of other projects 😢.

I think this problem may be related to #33, which is my next priority in the extension. I hope to be able to focus on this in the next week. So, stay tuned 😄 .
