### ISSUE TITLE
[BUG] - The custom gutter icons stopped showing

### ISSUE THREAD

**Issue by lastmartianlaboratory** [alefragnani/vscode-bookmarks#411]
**Environment/version**

- Extension version: 13.0.3
- VSCode version: 1.54.1 and up
- OS version: macOS Big Sur, WIndows 10

**Steps to reproduce**

1. Set `bookmarks.gutterIconPath` to a valid image path
2. Bookmarks become invisible

Custom icons stopped showing since the most recent updates (VSCode 1.54.1, 1.54.2)
Default bookmark icon shows Ok.

**Comment by alefragnani** [comment]
Hi @lastmartianlaboratory ,

It seems the latest VS Code release now _blocks_ loading resources from locations other than "VS Code controlled" ones. More info here https://github.com/microsoft/vscode/issues/118623.

I'm not a fan of copying the new icon to some controlled location, but it seems to be the only solution right now.

Hope this helps

**Comment by lastmartianlaboratory** [comment]
Thank you! That did the trick 👍

And if that's how VSCode handles resources now the `bookmarks.gutterIconPath` should probably have some sort of a note or removed altogether.

**Comment by alefragnani** [comment]
Yep, I'll take a look on alternatives.

**Comment by alefragnani** [comment]
I'm closing this issue in favor of #445, where you will be able to customize the Bookmark's icon appearance (fill and border colors), but not the icon itself.

I can leave the current `gutterIconPath` setting there, noted as _deprecated_, if you still use it. Otherwise you could simply move to the new settings when available.
