### ISSUE TITLE
Bookmark icons are missing

### ISSUE THREAD

**Issue by brentonhouse** [alefragnani/vscode-bookmarks#43]
The bookmarks function properly but there is no indicator. Using version 1.7.2 on OS X.

**Comment by alefragnani** [comment]
Hi @brentonhouse ,

It seems the same issue reported sometime ago (https://github.com/alefragnani/vscode-bookmarks/issues/34), caused by a bug in VSCode. It should be fixed now, at least in version 0.9.2 of the extension.

Are your extension updated?

**Comment by brentonhouse** [comment]
I am running version 0.10 of plugin.

**Comment by alefragnani** [comment]
Could you take a look at the *debug*? 

Open **Help / Toggle Developer Tools** and click in **Console** and check if there is any message about the extension. If you find, paste the message here.

**Comment by brentonhouse** [comment]
no messages...

**Comment by alefragnani** [comment]
In this case, I suggest you to reinstall the extension. Maybe something went wrong and the resources were not properly downloaded/installed.

But before that, you could _check_ the extension files. You just need to open the extensions folder (`Command Palette / Open Extensions Folder`), then navigate to `alefragnani.Bookmarks`. It should exists a folder called `images` and inside of it you should have a file called `bookmark.png`. This is the image to be displayed in the gutter.

Another thing that I remembered is about the **Themes**. Right at the beginning I noted a bug in _High Contrast _ thene. It was fixed in VSCode core. Are you using any custom Theme?

Hope this helps.

**Comment by alefragnani** [comment]
Hi @brentonhouse , any news?

**Comment by brentonhouse** [comment]
Tried uninstalling/reinstalling.  Also verified that the image exists in folder.  I am also not using high contrast theme.  No luck...

**Comment by brentonhouse** [comment]
It was working for me a while back (before I opened ticket) but not since.

**Comment by alefragnani** [comment]
I'm sorry about it. Unfortunately I don't have a Mac in hand to test (if this is OS related). I will try to get one from a friend and see if this happens there.

Let me know of any updates..

**Comment by alefragnani** [comment]
Hi @brentonhouse , are you still experiencing this issue? If yes, just out of curiosity, are you using a Retina Mac?

I remembered your issue when looking for #70 . Maybe, if that is the case, could fix your issue too.

**Comment by alefragnani** [comment]
Just released version 0.15.0 supporting SVG image as bookmarks. 
Could you check it?

**Comment by brentonhouse** [comment]
I've uninstalled and reinstalled but keep getting 0.14.1.   I will try again tomorrow to see if it is cached somewhere.  Thanks!

**Comment by brentonhouse** [comment]
Looks like 0.15.0 works!!! Thanks so much!!
