### ISSUE TITLE
[BUG] - Bookmark positions doesn't update after pasting above them

### ISSUE THREAD

**Issue by Ngranger** [alefragnani/vscode-bookmarks#446]
**Environment/version**

- Extension version: 13.1.0
- VSCode version: 1.57.1
- OS version: Windows_NT x64 10.0.19042

**Steps to reproduce**

1. Set labeled bookmarks (at least two).
2. Copy and paste several lines of code in between them.
3. The second bookmark onward should be shifted by the number of newlines, but the bookmarks remain at their previous line number(s).  But a manual addition of empty lines using the enter key does cause the bookmarks to move with their respective items.

**Comment by Ngranger** [comment]
Upon further incidents, it has become clear the problem lays in using the global replace functionality within a specific file causing the bookmarks to be misaligned compared to where they were placed.

**Comment by alefragnani** [comment]
Hi @Ngranger ,

First of all, sorry for the late reply.

It seems you are facing an issue with the _sticky_ behavior the Bookmarks have (follow the source changes), and maybe it's related to one of the already opened issues, specially because you said it _may be related to a specific file_. 

If the file/file type has a auto-formatter like prettier, you may be facing #118. Otherwise it could be a more generic issue, like #168.

I'm planning to revisit the _sticky_ behavior in order to better detect changes on file and properly update bookmark positions.

Hope this helps

**Comment by Ngranger** [comment]
While I've only noticed this issue in one file, I have no reason to believe it is file-specific in natural.  I think I've narrowed down what action seems to be causing the problem.

From my analysis, it only seems to happen when I do the following steps:

1. Create bookmarks in a given file.
2. Hit **_Ctrl+F_** to access the file-specific search/replace widget.
3. Perform a **_Replace All_** operation that changes code between any two bookmarks.

Eventually, I discover that my bookmarks in that particular file aren't aligned with the intend item anymore.  Hopefully, this will help with resolving this bug.  My recommendation, would be to keep track of the number of lines between each bookmark in a file, then on a **_Replace All_** command, compare the line count between each item and adjust as appropriate.
