### ISSUE TITLE
Publish to open-vsx.org?

### ISSUE THREAD

**Issue by hl2guide** [alefragnani/vscode-bookmarks#451]
Please consider publishing this extension to: https://open-vsx.org/

So that users of VSCodium can use it too.

**Comment by alefragnani** [comment]
Hi @hl2guide ,

There is already an open issue (#374 ) asking about open-vsx. 

BTW, it appears they republished the extension, because it is listed on their marketplace, at least today.

Just a side note, the extension was there up until a few months ago, when they decided force extension authors to sign/publish on their marketplace, removing the extensions from those that didn’t signed. Personally, I didn’t like that move.

You can keep downloading the `.vsix` files from the Release section on this repo. 

Hope this helps
