### ISSUE TITLE
[BUG] - Toggling bookmarks in notebook cells results in a duplicate editor being opened

### ISSUE THREAD

**Issue by DonJayamanne** [alefragnani/vscode-bookmarks#456]
**Environment/version**

- Extension version:13.1.0
- VSCode version: 1.59.0-insider (VS Code Insiders)
- OS version: Mac

**Steps to reproduce**

1. Install Jupyter extension or other extension that support notebooks
2. Create a notebook file *.ipynb
3. Add some code into a cell and toggle bookmarks
4. Notice how a duplicate editor is opened for the code cell.

Thanks for this great extension. I would have submitted a PR to resolve this, however it seems the code used to add bookmarks is closed source (or its just me being silly as I was unable to find the code)

![recording](https://user-images.githubusercontent.com/1948812/126592417-510fe694-2650-4876-b3a7-947973184cd3.gif)

**Comment by alefragnani** [comment]
Hi @DonJayamanne ,

I don’t use Notebooks that much, but I think I know what’s causing that. If that’s the case, it should be fixed in the next release.

Thanks for reporting

**Comment by alefragnani** [comment]
When I first saw your issue, I was wondering if #294 could be closed, but then I installed the **.NET Interactive Notebook** extension, and could see the extension is not working properly, unfortunately.

Even if the Bookmark can be added to the line, and being able to navigate between bookmarks on the same file, the `List from All Files` command and the Side Bar does not work. Mostly because the bookmarks are tied to the file (.ipynb) itself, not each Cell. So, Notebook support must be properly handled.

But, specifically about your issue, I just noticed it has been fixed while working on #440. So, it won't duplicate the editor anymore on the next release.

Hope this helps.
