### ISSUE TITLE
[FEATURE] - Display label text while hovering over the icon

### ISSUE THREAD

**Issue by iejepwy** [alefragnani/vscode-bookmarks#494]
Hi, Is there any possible to display label text while hovering over the icon ? I want to use this plugin as a notebook more than a bookmark.

**Comment by alefragnani** [comment]
Hi @iejepwy ,

This has been requested almost 3 ago (#19), but ended up being closed because the VSCode issues (new APIs) it depends on (https://github.com/microsoft/vscode/issues/28080) weren't released back then. 

In fact, the issues are still open and there is no API yet, so I guess it won't see the light any time soon.

Hope this helps

**Comment by alefragnani** [comment]
Looking closer to the VS Code issue, I can see it still has no update from VS Code team members for more than three years, and does not appear to be released anytime soon.

I'm subscribed to the issue, so if/when it is closed, I'll be notified.

Being said that, I'm closing the issue.
