### ISSUE TITLE
[BUG] - Bookmark deleted after git revert any changes on any non-bookmarked lines

### ISSUE THREAD

**Issue by elliotching** [alefragnani/vscode-bookmarks#507]
**Environment/version**

- Extension version: 13.2.2
- VSCode version: 1.63
- OS version: macOS 11.6.2

**Steps to reproduce**

0. enable "Bookmark > Experimental : new sticky engine" in setting
1. create an empty folder
2. init git inside that folder
3. create an empty file name `a.txt` and type more then 10 lines in `a.txt` file
4. git commit that file (commit in local only)
5. make 1 to 3 bookmarks on any lines on `a.txt`
6. make some changes on any lines that are **not bookmarked**
7. using VSCode util to git revert the changes lines
8. observe the bookmarks made on step 5 are missing.

https://user-images.githubusercontent.com/20972678/151117799-df53ab8e-4a04-4aef-8a12-cc3e14f35b69.mov

**Comment by alefragnani** [comment]
Hi @elliotching ,

The bookmarks lost sync because Git operations (even those fired by VS Code commands) updates the file outside the context of the text editor, and the extension only recognizes changes made by the user while editing files. If instead of reverting the changes using Git command, you use Undo command, the support is better. Similar issues were reported in https://github.com/alefragnani/vscode-bookmarks/issues/604, https://github.com/alefragnani/vscode-bookmarks/issues/224 and https://github.com/alefragnani/vscode-bookmarks/issues/177,

Right now, I have no plans support git operations, as I'm planning to focus on other areas of the extension. But I'm aware of the limitation, and once I'm able to improve the sticky behavior, Git support is the next objective.

Thanks for your understanding.
