### ISSUE TITLE
[feature request] interaction with FIND

### ISSUE THREAD

**Issue by hp48gx** [alefragnani/vscode-bookmarks#514]
There's a famous text editor for Windows that offers a very good implementation of bookmarks:
https://textpad.com/products/textpad/features

In particular, a _tremendously_ useful feature is the ability to bookmark automatically all the results of a search.
Not sure if it's technically possible... can we get something similar here?

**Comment by alefragnani** [comment]
Hi @hp48gx ,

This was one of the first features someone asked for #7, but VS Code didn't provide an API back then. In the end, they closed the API request using a different approach (add support to extensions to run _find_), so nothing changed.

In the end, I gave up on waiting for the API and added multi-selection support #77. So, instead of simply use the search results, you just _select them_ and while togging bookmarks, it will toggle for every selection.

Hope this helps
