### ISSUE TITLE
[BUG] - probably a bad idea to have the shortcut cmd+alt+L for "jump to next bookmark"

### ISSUE THREAD

**Issue by lingtalfi** [alefragnani/vscode-bookmarks#520]
Hi, I'm a mac user.
On mac the key command to write a pipe is cmd + alt + L,
which happens to also be the default shortcut of vscode-bookmarks for "jump to next bookmark".

This is not a big trouble, I can just remove/edit the offending keybinding (since obviously I need to be able to type pipes when coding), but I just wanted to let you know (in case you didn't), and also suggest considering using other default shortcuts, if that makes sense.

Cheers.

**Comment by lingtalfi** [comment]
sorry, actually it's alt + shift + L (for the pipe) which conflicts with "expand selection to next" (from vscode-bookmarks)

**Comment by alefragnani** [comment]
Hi @lingtalfi ,

I would say a “bad idea” was, TBH, to add _any_ shortcut at all 😆 .

When I created the extension, I only have Windows available, so any MacOS or Linux shortcut, weren’t of my knowledge. In fact, not only OSes has its own native shortcuts, but different keyboard layouts too. So, it’s really difficult to avoid every native shortcut. 

What I do now (after a few issues with shortcuts on my extensions) is not deliver default shortcuts anymore. 

As you said, you can customize any shortcut, and in the end, this is how users should do. I can’t change/remove the default shortcuts, otherwise every current user could be affected.

Hope this helps

**Comment by bonatoc** [comment]
Your extension is really nice, but I think you grossly underestimate how much developers use Macs.
It **is** a bad idea.

You just can't make your keyboard shortcuts conflict with the pipe symbol on MacOS.
I would change from "L" to "M", and alert the existing users on the next release of the change.

Otherwise, it looks like you could take the OS into account. 
See "Conditional operators" [on this page](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts).
![image](https://user-images.githubusercontent.com/956531/189265135-8ffae1a8-e1d2-4f37-8070-988373240f60.png)

**Comment by alefragnani** [comment]
Maybe you didn't fully read my previous comment, but I described that _when I created the extension, I only had Windows available_. That's the reason why I didn't know the shortcuts that MacOS or Linux distros/window managers had. And BTW, the `conditionals` you described, weren't all available back then, specially the OS identities. So, even if I had a MacOS, I wouldn't be able to create different shortcuts for each OS. Not to mention different keyboard layouts.

I didn't _grossly underestimated_ MacOS users as you said. I simply had no way to validate the shortcuts on MacOS or any of the zillion of Linux distros/window managers, because I had none of them.

I'm sorry, but I won't change the shortcuts, for the reasons described in the previous comment. If it conflicts with your OS or any other tool/extension you use, you should remove or customize the shortcut.
