### ISSUE TITLE
[BUG] - Bookmarks vanished

### ISSUE THREAD

**Issue by jano23** [alefragnani/vscode-bookmarks#538]
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Steps to reproduce**

1.  Open VSCode > open file that had bookmarks > click on the Bookmarks icon OR,  use "Bookmarks: List from All Files" command
2.  No bookmarks show

**Comment by alefragnani** [comment]
Hi @jano23 ,

I'm sorry to hear that. 

Could you provide more details? 
* Where the projects is stored: local, external drive or remotes (like Docker, SSH, WSL).
* How are you `bookmarks` settings defined?
* Did you update VS Code or your OS prior _vanishing_

Be aware that Bookmarks are stored _per project_ by default, which means it stores different bookmarks data for each folder (full path) you open. If you copy the same folder to other location and open it in VS Code, the _previous_ bookmarks are not restored, because this new folder is exactly this, a new folder. The same happens if you rename the folder (or any parent folder). VS Code will handle each folder as a separate _location_

Hope this helps

**Comment by jano23** [comment]
projects are located locally on my C:\ drive and I haven't changed their
location in years.
I update VS Code as soon as they post updates. So my guess is yes, I did
before they disappeared.
I'm including a screenshot of the settings:

[image: Screenshot 2022-05-25 180449.jpg]

**Comment by alefragnani** [comment]
I guess images are not attached when you answer using email, so I can’t see it.

Anyway, if your project are _local_ and you didn’t change its location, I can only guess two alternatives:

1. Something _crashed_ bookmarks data. Its data is located using VS Code internals API (a SQLite database shared by every extension and VS Code itself).
1. Something _happened_ while opening the folder and the extension failed to load the bookmarks.  

It the failure is happening _for every project you have_, I suppose option 1. 
If the failure is on only _for some projects_, I suppose option 2.

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Comment by jano23** [comment]
Thanks Alessandro,

I am going to recreate them and see how it goes from now on
