### ISSUE TITLE
[Question][ Suggestion] Displays bookmarks in the minimap

### ISSUE THREAD

**Issue by Tekbr** [alefragnani/vscode-bookmarks#54]
- VSCode Version: 1.10.0 - insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

With the support for the [minimap in vscode](https://github.com/Microsoft/vscode/issues/4865), is it possible to add the tags in the minimap? Similar to [minimap-bookmarks package](https://atom.io/packages/minimap-bookmarks).

**Comment by alefragnani** [comment]
Hi @Tekbr ,

It appears the minimap feature didn't support the `decorator` API, neither publish any new API to do anything like that. I added a comment in the referred issue, so let's wait to see how the feature evolve.

Hope this helps

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/20934

**Comment by alefragnani** [comment]
Hi @Tekbr ,

Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.

I'm closing this issue because the VS Code issue that it depends on, has no update from VS Code team members for more than an years. It is planned on "Backlog" Milestone, so it appear it will not be released soon. I'm subscribed to that issue, so if/when it is closed, I'll be notified.

**Comment by Tekbr** [comment]
@alefragnani Ok. Obrigado pela atenção. 

-- Sorry for the English, I used Google Translator --

OK thank you for the attention.

**Comment by pksunkara** [comment]
That feature seems to have been merged in vscode

**Comment by alefragnani** [comment]
Hi @pksunkara ,

The VS Code feature yes, but the API for extension developers, not at all. There are at least two issues (#82808 and #73140 - commented there) which are still open, unfortunately.
