### ISSUE TITLE
[BUG] - Bookmark doesn't move with the code when pressing the Enter key

### ISSUE THREAD

**Issue by heathbo1** [alefragnani/vscode-bookmarks#540]
This has been an amazing extension.  For some reason now, any bookmark I create doesn't move to the next line with the code when I press the Enter key. This happens whether I save the change or not.  When I press Enter, I see the bookmark move to the next line, then jump back to the previous line.

I am using Angular(8.2.14), Typescript(3.5.3), Prettier(2.5.1) in VS Code 1.67.1 on Windows 10.  Prettier is set to format on save.

**Comment by alefragnani** [comment]
Hi @heathbo1 ,

That's really weird, because the extension didn't have any update on that feature for a while. Maybe something changed in VS Code itself or Prettier, and is causing this side effect.

I don't use Prettier for a while, so I would ask you to turn it off to see if the error persists. Also, could you please provide more details about how is your source when the error happens. Maybe a print screen or a screen capture showing the error. Sometimes peculiarities in the source code structure (empty lines, indentation, etc) may also influence how the extension works.

Thanks in advance

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
