### ISSUE TITLE
[BUG] - Bookmarks prevent clicks on breakpoints

### ISSUE THREAD

**Issue by shaonianruntu** [alefragnani/vscode-bookmarks#551]
**Environment/version**

- Extension version: 13.3.1
- VSCode version: 1.70.1
- OS version: Windows10 21H2 19044.1826

**Steps to reproduce**

Normally, a click can creates a breakpoint, and clicks the breakpoint again can cancel it.

But when a bookmark is created on the line where the breakpoint is located, the bookmark will overwrite the layer of the breakpoint, and clicking the created breakpoint again cannot cancel it. 
You can continue to cancel the breakpoint by clicking only if you unbookmark the current line first.

![image](https://user-images.githubusercontent.com/16336682/184085850-2600991f-78b7-4599-85be-5bd9ccf9df7a.png)

I think it's a bug, bookmarks shouldn't override mouse actions on the current line breakpoint.

Hoping to fix it,

Thanks & Regards
Nan

**Comment by fade2gray** [comment]
You can use the `Run -> Toggle Breakpoint` from the menu, or use the `F9` hotkey.

**Comment by alefragnani** [comment]
Hi @shaonianruntu ,

This issue is caused by VS Code (first reported in #56), and unfortunately, there is nothing I can do on my side. The extension doesn't have any control about the _click_ event. In fact, I wish I had, because I could add a _add bookmark with mouse click_ option 😃 

It is being tracked in https://github.com/microsoft/vscode/issues/5923, and besides the original _visual_ issue has been partially solved by VS Code, the _click_ still doesn't.

So, we just have to wait until VS Code itself fixes it, or expose any click event handler to extensions.

Hope this helps

@fade2gray thanks for the tip 👍

**Comment by shaonianruntu** [comment]
> Hi @shaonianruntu ,
> 
> This issue is caused by VS Code (first reported in #56), and unfortunately, there is nothing I can do on my side. The extension doesn't have any control about the _click_ event. In fact, I wish I had, because I could add a _add bookmark with mouse click_ option 😃
> 
> It is being tracked in [microsoft/vscode#5923](https://github.com/microsoft/vscode/issues/5923), and besides the original _visual_ issue has been partially solved by VS Code, the _click_ still doesn't.
> 
> So, we just have to wait until VS Code itself fixes it, or expose any click event handler to extensions.
> 
> Hope this helps
> 
> @fade2gray thanks for the tip 👍

Thank you very much for your detail reply.

Hahaha, I am real confused why we can't add a breakpoint by mouse click before. Seems it is a missing function of VSCode.

Thank you

**Comment by sslupsky** [comment]
@alefragnani What about the margin on the other side of the line number where the open / close controls are located?  Can you get a click event there?  If that is possible, maybe it is possible to move the bookmark here instead of using the gutter?

**Comment by alefragnani** [comment]
Hi @sslupsky , unfortunately no, it is not possible either.
