### ISSUE TITLE
Bookmarks not working on big files(?)

### ISSUE THREAD

**Issue by emarsk** [alefragnani/vscode-bookmarks#553]
If I try to toggle a bookmark in a very large file (>1,200,000 lines, 78MB), I get the error "Open a file first to toggle bookmarks".

The size of the file is the only feature I can think of that is different from the other text files in the same folder.

If there's an unfixable technical limitation in place, it would be desirable to at least see an appropriate error message.

**Comment by alefragnani** [comment]
Hi @emarsk ,

Yes, this is a known VS Code limitation, which makes large files invisible to extensions. The first issue was #31.

Unfortunately, there is nothing I can do in the extension to avoid/detect such situation, because VS Code itself does not _tell_ the extensions that an unsupported file is being loaded. So, we will have to wait until VS Code team expand/remove such limitation.

Hope this helps
