### ISSUE TITLE
[BUG] - Bookmark on a line prevents click to toggle breakpoint

### ISSUE THREAD

**Issue by jez9999** [alefragnani/vscode-bookmarks#555]
When a line is bookmarked, the bookmark appears behind a debug breakpoint (red dot).  You then can't click the red dot to toggle it on/off.

**Comment by alefragnani** [comment]
Hi @jez9999 ,

This issue is caused by VS Code (first reported in #56), and unfortunately, there is nothing I can do on my side. The extension doesn't have any control about the _click_ event. In fact, I wish I had, because I could add a _add bookmark with mouse click_ option 😃 

It is being tracked in https://github.com/microsoft/vscode/issues/5923, and besides the original _visual_ issue has been partially solved by VS Code, the _click_ still doesn't.

So, we just have to wait until VS Code itself fixes it, or expose any click event handler to extensions.

Hope this helps
