### ISSUE TITLE
[FEATURE] - please add a shortcut for `Edit Label`

### ISSUE THREAD

**Issue by hitzhangjie** [alefragnani/vscode-bookmarks#567]
Please add a shortcut for `Edit Label`. 
Add bookmarks is very common, if we need to relabel it conveniently, a shortcut is better.

**Comment by alefragnani** [comment]
Hi @hitzhangjie ,

The `Edit Label` command, available in the Side Bar, cannot have shortcuts assigned because it depends on the _selected_ bookmark in the Side Bar.

But, you can assign any shortcut to the `Bookmarks: Toggle Labeled` command, which will allow you to edit the label of the the bookmark where the cursor is located. Simply use the native Key Bindings feature (https://code.visualstudio.com/docs/getstarted/keybindings) and define any shortcut you want.

Hope this helps.
