### ISSUE TITLE
[REQUEST]Convert Search Results to Bookmarks

### ISSUE THREAD

**Issue by raedwa01** [alefragnani/vscode-bookmarks#571]
First off, congrats on the great extension.  I don't think I saw this as a request yet.  When I am working on a project and I want to find everything related to the "product" object for example, I would usually just use the search box to search my code for "product", double click one of the results, and navigate to that item.  The problem is, if I need to search for another piece, say the method calls another method, i lose the results.

Currently, I have to go result by result, click the line in the editor, and toggle the bookmark.  Is there a way to convert all the items in the search results to bookmarks?  Or even just right click on each result in the search and toggle there?  Would make removing the need to search over and over easier.

**Comment by alefragnani** [comment]
Hi @raedwa01 ,

First of all, thank you! I'm glad to know you like the extension.

About your request, yes, it has already been made before. In fact, it was one of the first requests to the extension #7, but unfortunately, it was never possible to develop it because a missing API. There is no way to _load_ to the search results in order to create bookmarks for every match.

It's been a while I don't revisit this topic, so I'm not sure there is an alternative way to accomplish this. I'll take a look again, and if I see something promising, this could be planned for future releases.

Hope this helps

**Comment by alefragnani** [comment]
Unfortunately, I couldn’t find any API to accomplish such feature.

That being said, the issue will be closed

Thanks for your understanding.
