### ISSUE TITLE
[BUG] - Toggle bookmark shortcut does not work on .txt files

### ISSUE THREAD

**Issue by joshuachough** [alefragnani/vscode-bookmarks#591]
**Version: 1.74.3 (Universal)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:07:18.579Z (1 mo ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No**

- Extension version: v13.3.1
- VSCode version: 1.74.3 (Universal)
- OS version: Darwin arm64 22.3.0

**Steps to reproduce**

1. Go to any `.txt` file
2. Hit `Option + Cmd + K`
3. It does not toggle a bookmark

Note: what does work is using the sidebar toggle bookmark button.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/34778271/220188097-307b0b40-2d2c-432d-9290-cde8ba50c1aa.png">

**Comment by alefragnani** [comment]
Hi @itsjoshthedeveloper ,

There is no _blocking_ from toggling bookmark on `.txt` or any other filetype, except binaries, because are not natively opened in VS Code regular editor.

And, as you said the button in the Side Bar works, I suppose there is some problem (conflict) with the keyboard shortcut. Maybe a conflict with another extension that you have installed, or even the keyboard layout you use. 

I suggest you to try using the command via Command Palette, to see if it works. If yes, try opening the `Preferences: Open Keyboard Shortcuts` command, and look for commands with the `cmd option k` shortcut. Maybe you have more than just `Bookmarks: Toggle` command. So, simply change the shortcut to some other that does not conflict

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
