### ISSUE TITLE
[BUG] - Can't reliably put bookmarks after updating vs code [Workaround provided]

### ISSUE THREAD

**Issue by Raikiri** [alefragnani/vscode-bookmarks#599]
**Environment/version**
After updating to vscode 1.76 (I was running 1.70 before, so any version inbetween could have caused the issue) I noticed that bookmarks can no longer be placed consistently. They end up sometimes placed, but at a previous line. For example:
- [Bookmarks: Toggle] @ line 5 (nothing happens)
- [Bookmarks: Toggle] @ line 7 (nothing happens)
- [Bookmarks: Toggle] @ line 10 (bookmarks at line 5 and 7 appear)
The behaviour is very inconsistent and hard to track exact logic of, but in practice it's next to impossible to put bookmarks where you want them to go. They can be removed perfectly fine, but placement seems to be bugged.

However, there are two workarounds that I found:
1) [Bookmarks: Toggle Labelled] seems to work just fine
2) I uninstalled the extension, restarted vs code and reinstalled the extension back -- this solved the issue entirely, bookmarks seem to be working after this.

I guess for me the problem is solved, but I thought it's worth letting people know that the problem exists, provide a workaround and hopefully help people track down why it's happening in the first place.

**Comment by alefragnani** [comment]
Hi @Raikiri ,

Thank you for reporting the issue and the fix. 

It is rare, but sometimes not only VS Code updates but also extension auto-updates cause issues in the extension, and you have to use the same _workaround_ in order to be back on track.

I'm closing the issue, but I'll let it noted to future references when someone reports similar issues.

Thank you
I'm closing the
