### ISSUE TITLE
[BUG] -After fixing the conflict, the bookmark position is misaligned

### ISSUE THREAD

**Issue by yc283200832** [alefragnani/vscode-bookmarks#604]
**Environment/version**

- Extension version:
- VSCode version: 
- OS version:

**Steps to reproduce**

1. 
2.

**Comment by alefragnani** [comment]
Hi @yc283200832 ,

This happens because the conflict is managed _outside_ VS Code (Git itself) and so, the extension does not know how to update the bookmark position. Only operations made by VS Code itself are monitored.

I'm planning to review this concept in the future, but nothing official/ETA yet. If this really happen, this scenario would be supported.

Hope this helps
