### ISSUE TITLE
[FEATURE] - Allow to work with bookmark sets

### ISSUE THREAD

**Issue by Chezzie** [alefragnani/vscode-bookmarks#622]
Thank you for the great work!

When I am switching between branches, I use different sets of bookmarks.
It will be wonderful if there will be an option to switch between bookmark sets, like: assign them to the branch names, and/or stash/unstash them, or simply file export/import.

Ideally, I'd like to have a flag for bookmarks:
a) persistent
b) assigned to a branch name (nice to have a default)

VSCode provides common VCS API AFAIK.

**Comment by alefragnani** [comment]
Hi @Chezzie ,

If you have a deep connection between your bookmarks and a branch, I would suggest you to use `bookmarks.saveBookmarksInProject` setting as `true`, as it would save the bookmarks within the project folder in `.vscode/bookmarks.json` file.

Otherwise, there is a **Tags** feature to be added, being tracked in #254 , more detailed at https://github.com/alefragnani/vscode-bookmarks/issues/254#issuecomment-914523838. With that, you will be able to apply a **Tag** to bookmarks and switch/activate sets whenever necessary.

Hope this helps

**Comment by Chezzie** [comment]
Thank you! This will work for me as well)

сб, 8 июл. 2023 г., 14:02 Alessandro Fragnani ***@***.***>:
