### ISSUE TITLE
[FEATURE] - TODO as trigger for auto bookmark

### ISSUE THREAD

**Issue by zxmaster** [alefragnani/vscode-bookmarks#647]
Hi there!

Is it possible to implement such a feature:

Once I type TODO inside the comment section of a language of some special pattern it will create auto bookmark. It might have special dedicated "TODO tree" for that.

**Comment by alefragnani** [comment]
Hi @zxmaster ,

The idea behind the Bookmarks extension is that you define the positions which you think to be important, and to do that, you have to be there.

Instead of a new command to add bookmarks based on some special token/word, I suggest you to do the opposite. Search for any TODO in the file, and use the multi-cursor feature in extension to bookmark all locations at once.

But, if you need bookmark/tag locations from the entire workspace (not just the active file), I remember seeing a few extensions that uses regex to do that. If I remember correctly, mostly uses the to-do concept. 

* https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
* https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus

Hope this helps
