### ISSUE TITLE
[BUG] - Bookmarks sidebar option not there anymore

### ISSUE THREAD

**Issue by stephanieraymos** [alefragnani/vscode-bookmarks#648]
- Extension version: v13.4.1
- VSCode version: Version: 1.82.2 (Universal)
- OS version: Sonoma

**Steps to reproduce**
Bookmarks icon used to show in sidebar, now it's not there, and it's not an option when i left click to see the ones that are checked to show in the sidebar.
I have nothing in my settings.json that disables this. 

I found something from 2021 that suggested to uninstall, close all vscode windows and then reinstall the extension. That did not work.

**Comment by alefragnani** [comment]
Hi @stephanieraymos ,

Is the extension itself still working? I mean, does its commands are available in the `Command Palette` and still works?

If the answer is yes, I suggest you to call the `Bookmarks: Focus on Explorer View` command, via `Command Palette`. It is a built in command, created by VS Code. which should focus/display the Bookmarks Explorer View. Doing so, it should display where it is. 

If this does not work, I suggest you to call the `View: Reset View Locations` command, via `Command Palette`. This command will (as it name says) reset any reorg you may have made on your views (any view) to its _default_ location. This _should_ work.

If it does not work, you should follow the uninstall process already mentioned on older posts. But, be sure to follow all the steps, in special the one that says you should _Close All VS Code Windows_. This is required because, unless you really close all VS Code windows, VS Code will not delete the uninstalled extension, and any reinstall would be simply reactivate the extension.

Hope this helps

**Comment by stephanieraymos** [comment]
Thank you! The first command popped open bookmarks in sidebar but didn't actually show my bookmarks. The second command to reset view locations worked! It's there now. Thank you!
