### ISSUE TITLE
Saving Bookmarks to project

### ISSUE THREAD

**Issue by fgarcia** [alefragnani/vscode-bookmarks#65]
The setting "bookmarks.saveBookmarksInProject" to true is partially broken

The functionality is OK, but the saved file assumes a Windows based filesystem, not a Unix one. To make it short, enabling this on Mac creates this file:

```
> ls -l
drwxr-xr-x     2 fgarcia  staff     136 Apr  9 12:50 .vscode
-rw-r--r--       1 fgarcia  staff      20 Apr 12 11:31 .vscode\bookmarks.json
```

I assume the extension wants to save `bookmarks.json` **inside** the `.vscode` folder, not net to it with an inverted slash encoded into the filename

**Comment by alefragnani** [comment]
Hi @fgarcia ,

You are right. The file should be saved **inside** `.vscode` folder, present in the current project. So for instance, if you open the folder `/Users/fgarcia/projects/newproject`, the bookmarks should be in `/Users/fgarcia/projects/newproject/.vscode/bookmarks.json`.

That's weird, because I already used the same syntax before while joining paths, without any problem. Maybe something changed or maybe no _non-Windows_ user has seen that before. I will make some changes that should avoid this.

Thanks for reporting

**Comment by fzzr-** [comment]
fixed in https://github.com/alefragnani/vscode-bookmarks/pull/67 , plz test it.

**Comment by alefragnani** [comment]
Also fix when _no folder is opened_ ...

**Comment by fgarcia** [comment]
amazing quick reaction to this bug!
I've verified the fix. Looks OK

**Comment by alefragnani** [comment]
Big thanks to @fzzr- for the PR 👏

**Comment by fzzr-** [comment]
Thanks for your hard work and cool extension!
