### ISSUE TITLE
[FEATURE] - Keep the text while input label

### ISSUE THREAD

**Issue by Erimus-Koo** [alefragnani/vscode-bookmarks#651]
- When creating a new bookmark, the name of the bookmark is taken from the text in line. After clicking "edit," you will see a blank input area. I hope that the previous text can be retained.
- If you directly create a bookmark with a label, it will also have a blank input field.

**Comment by alefragnani** [comment]
Hi @Erimus-Koo ,

I'm not sure I did understand your scenarios/steps correctly, as I couldn't reproduce it, so I have a few questions:

* Could you please indicate what is the value of `bookmarks.label.suggestion' setting? 
* When you say _ after clicking "edit", you will see a blank input area_. By _clicking "edit"_ do you mean using the Edit button/command in the Bookmarks Side Bar, or running the `Bookmarks: Toggle Labeled` command?

Thanks in advance

**Comment by Erimus-Koo** [comment]
## Case 1
1. `cmd+opt+K` toggle a bookmark on.
<img width="307" alt="image" src="https://github.com/alefragnani/vscode-bookmarks/assets/17139670/b70557c1-57d0-4629-be2d-ad8f0ae5f782">

2. Try to edit it. Click the pencil icon and get a blank input.
<img width="581" alt="image" src="https://github.com/alefragnani/vscode-bookmarks/assets/17139670/1337d897-8ffe-48f2-9477-62a001c626ae">

3. I hope the input includes `const initHandler = (`

## Case 2
Directly right-click at the left of the line number, and create a bookmark with label, same as the previous step 2.

---

And I have already checked `Use Workaround For Formatters`, but the bookmarks still frequently shift a few lines, which really has a significant impact.

In addition, if toggle bookmark is pressed in a multi-cursor situation, it will add many bookmarks that cannot be undone. It may be worth considering adding an option to disable this behavior.

**Comment by Erimus-Koo** [comment]
> And I have already checked Use Workaround For Formatters, but the bookmarks still frequently shift a few lines, which really has a significant impact.

This situation often occurs when there are too many function parameters. Prittier automatically splits the parameters into multiple lines or merges them into fewer lines if the number of parameters decreases, causing the bookmark to be offset.

**Comment by alefragnani** [comment]
Hi @Erimus-Koo ,

The **Case 1** is the _expected behavior_, as the idea of the `Edit Label` button is to edit the label of the bookmark. In this case, you have a regular bookmark (without label) and the _preview_ shown in the side bar is just the _line content_. When you click the `Edit Label` button, since the bookmark is not labeled, it will not _suggest_ any label. The `bookmarks.label.suggestion` setting only works for _selections_, which is not the case.

The **Case 2**, on the other hand, I couldn't reproduce the issue. When I click the `Edit Label` button on a labeled bookmark, its label is shown in the Input Box

![image](https://github.com/alefragnani/vscode-bookmarks/assets/3781424/d09def63-e5bc-461b-83fd-c55bdb1ce019)

Are you sure you edited a labeled bookmark? It has a ✏️  icon side by side the bookmark icon in the side bar.

About the bookmark shifting while using Prettier, and the setting to disable multi-cursor support, I'll open two separate issues to track.

Hope this helps

**Comment by Erimus-Koo** [comment]
Yeah, in case 2, I'm creating a new bookmark with the label, not editing a labeled bookmark, so it's the same issue about the **suggest**. I prefer to keep the content of the line as suggestion.

And in my usage, I find an automatically generated and updated TOC for functions that will be very helpful. It would be great if this could be a feature.

**Comment by alefragnani** [comment]
For your case 2, if you like the suggestion to be the _line content_, I suggest you to try out the following setting:

```json
    "bookmarks.label.suggestion": "suggestWhenSelectedOrLineWhenNoSelected",
```

As it, _Suggests the selected text _(if available)_ or the entire line (when has no selection). You still need to confirm_

Hope this helps
