### ISSUE TITLE
[FEATURE] Hover on bookmark icon to show the content of the bookmark

### ISSUE THREAD

**Issue by IsLand-x** [alefragnani/vscode-bookmarks#661]
Hello Fragnani, thanks for your great work!

The bookmark extension is very useful when I read the source code, I can mark the confusing code and ask the author later. But when I show the source code to others where bookmarked, I hover on the icon and the title doesn't show up. So I have to open the bookmark browser on the sidebar, and find the bookmark by filename and location manually.

I think it will be more convenient if this feature was completed.

Also, I found the earlier issues where you said the reason you didn't develop the feature is the absence of vscode api.

https://github.com/alefragnani/vscode-bookmarks/issues/494
https://github.com/alefragnani/vscode-bookmarks/issues/375

I found the issue below in vscode's repository, and a comment seems already completed the gutter hover feature. So maybe today's vscode api is capable for developing the hover feature of bookmark extension. Hoping it can bring you some idea~

https://github.com/microsoft/vscode/issues/5455#issuecomment-1101777685

Also, I am interested in developing the feature if the vscode-bookmark-core repository can be set to public.

Thanks again, and hoping this feature can be completed by you and the community.

**Comment by alefragnani** [comment]
Hi @IsLand-x ,

First of all, thank you for your kind words. I'm glad to know the extension is helpful!

About the feature, in fact, the video on that comment is not displaying an icon in the gutter (with the line numbers), but in the text area, moving the text itself a bit to the right. If you use the GitLens extension, it is like the `GitLens: Toggle File Blame` command.

The original issue that asks for hover in the gutter is still open in VS Code repo https://github.com/microsoft/vscode/issues/28080. But, I have the feeling that it could come to their backlog in the near future, since the _mouse click_ API was added recently. 

Hope this helps

**Comment by nolimitdev** [comment]
If hover is not support by VSCode what about for example click and show in some dialog/modal window etc.? It is really frustrating to see icon that there is a bookmark but can not see label! I feel like blind man.
