### ISSUE TITLE
[FEATURE] - I lost the bookmarks I had set, there is not a way to synchronize them

### ISSUE THREAD

**Issue by Mauroariza** [alefragnani/vscode-bookmarks#675]
I was settinG all my bookmarks.. but today I opened visual studio and all the bookmarks dessapear... I just made a git pull to my files... with only one change.. but I lost all the bookmarks.

**Comment by chy2948331536** [comment]
bookmarks extension setting->enable Save Bookmarks In Project it will create a bookmarks.json in the .vscode folder

**Comment by Sodj** [comment]
I recommend going to the settings and enabling the check box that says keep bookmark on line delete.
That's what was removing my bookmarks

**Comment by alefragnani** [comment]
Hi @Mauroariza ,

The bookmarks _may be lost_ because Git operations are managed outside VS Code, and the extension only recognizes changes made by the user while editing files. Similar issues were reported in https://github.com/alefragnani/vscode-bookmarks/issues/604, https://github.com/alefragnani/vscode-bookmarks/issues/507, https://github.com/alefragnani/vscode-bookmarks/issues/224 and https://github.com/alefragnani/vscode-bookmarks/issues/177. As @chy2948331536  and @Sodj  suggested, you could set bookmarks to be saved within the project folder and keep them stored in your git repo, so whenever you pull changes or switch branches, there is less chance bookmarks to be out of sync.

Hope this helps
