### ISSUE TITLE
[FEATURE] - reqest import/export bookmark feature

### ISSUE THREAD

**Issue by shenxiaolong-code** [alefragnani/vscode-bookmarks#682]
1. need import/export bookmark feature -- better to save files.
2. It is better to list all bookmark files, user can double-click to load/switch bookmark file.
3. It is better to rename the bookmark by key F2, like renaming the file name.

**Comment by pcandido** [comment]
+1 to import/export

**Comment by 5z1punch** [comment]
need the feature to import/export

**Comment by alefragnani** [comment]
Hi @shenxiaolong-code ,

When opening issues, please split each request in a separate issue, as becomes easier to evaluate each one when individually. 

Specifically the first one (Import / export) is already being tracked in #172.  The second one, I didn't understand what you mean, so I would ask you to provide more details. The third one, I'm not sure this is possible, as focusing the view itself (in order to be able to hit F2 or any other keyboard shortcut) is not straighforward, since when you click a bookmark, the focus is moved to the editor (to focus the location).

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if you can provide more details

Thanks for your understanding
