### ISSUE TITLE
[FEATURE] - Display label text on icon click in the gutter

### ISSUE THREAD

**Issue by nolimitdev** [alefragnani/vscode-bookmarks#688]
Since similar feature requests were closed because of missing VSCode API with hover over the icon in the gutter (with the line numbers) Im adding new feature request but with "click" not "hover" because as mentioned here https://github.com/alefragnani/vscode-bookmarks/issues/661#issuecomment-1802228894 `mouse click API was added`.

**Comment by alefragnani** [comment]
Hi @nolimitdev ,

The _mouse click_ that it referes to corresponds to the _right click_, in order to display the context menu. It is not the regular mouse click, unfortunately.

I was reevaluating the open issues about displaying labeled bookmarks, playing a bit with the current APIs and noticed that besides #602, a _hover_ (like https://code.visualstudio.com/api/language-extensions/programmatic-language-features#show-hovers) could be added the bookmarked lines. But in order to avoid mixing bookmark labels with already existing source code hovers, maybe the bookmark hover could be fired in _specific regions_ of the line, like closer to the gutter (first N chars). So, when hovering the mouse on that location, the bookmark label could be displayed.

Other than this, and #602, I see no reasonable way to display the bookmark label _inside_ the source.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen if you have new comments to add.

Thanks for your understanding

**Comment by nolimitdev** [comment]
I do not see any question above.
