### ISSUE TITLE
[BUG] - Bookmarks desync when performing git commands

### ISSUE THREAD

**Issue by Stratoscaster** [alefragnani/vscode-bookmarks#698]
Bookmarks move to bottom of page, if "Keep Bookmarks On Line Delete" is enabled, when using `git checkout` for example. If "Keep Bookmarks On Line Delete" is disabled, the bookmarks disappear, otherwise the bookmarks move to the bottom of the page as the file updates between branch changes.
**Steps to reproduce**

1. Create a git repo with a file
2. Make a commit of that file with a few lines of text in it
3. Create a new branch and checkout into it
4. Make a change to that new branch and commit
5. Checkout your original master branch (or any other branch)
6. The bookmarks will move to the bottom of your file or be deleted entirely once the file updates.

I really like this extension and would love to be able to use it, however this bug makes it not usable for me. Thank you!

**Comment by Stratoscaster** [comment]
Just had a thought: it might be possible to fix this via only saving to bookmarks.json when there are no running operations (after files save for example)

**Comment by alefragnani** [comment]
HI @Stratoscaster ,

The bookmarks lost sync not because the `bookmarks.keepBookmarksOnLineDelete` setting, but because Git operations are managed outside VS Code, and the extension only recognizes changes made by the user while editing files. Similar issues were reported in #604, #507, #224 and #177, 

Right now, I have no plans support git operations, as I'm planning to focus on other areas of the extension. 

Thanks for your understanding.
