### ISSUE TITLE
Possible to bookmark all search results?

### ISSUE THREAD

**Issue by factormystic** [alefragnani/vscode-bookmarks#7]
I don't know if this kind of integration is possible, but it'd be handy if so

**Comment by alefragnani** [comment]
Really interesting. I will investigate the API about this.

**Comment by Nimzozo** [comment]
:+1:  +1

**Comment by laggingreflex** [comment]
Came here looking for same. My use case in sublime was to bookmark all selected occurrences of some text (when search and replace just wouldn't do and you have to go to them all manually). 

This would be extremely useful. +1

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/9049

**Comment by alefragnani** [comment]
Hi,

Instead of waiting for a VS Code API, I think that #77 would give a similar result.

You _search for something_, select all occurrences and hit `Toggle Bookmark` to bookmark all selected lines.

I know that #77 is just for _the current file_, and this issue would be for _search tab_, but hey, it's better than wait for the API 😄 

What do you think?

**Comment by alefragnani** [comment]
Closing it in favor of #77

**Comment by MagTun** [comment]
> You _search for something_, select all occurrences and hit `Toggle Bookmark` to bookmark all selected lines.

The "select all occurences" is done by press Alt+enter in the search field (cf https://stackoverflow.com/a/42213155/3154274)
