### ISSUE TITLE
v0.15.0 shows "Reload" all the time after installing from local file (VSCode)

### ISSUE THREAD

**Issue by mrkafk** [alefragnani/vscode-bookmarks#71]
I have compiled VSCode from source (company requirements). `v0.14.0` works fine, but `v0.15.0` after installing from `.vsix` has "Reload" button in extensions list all the time, regardless of VSCode restarts.

VSCode: 1.12.2
Node.js: 7.9.0

**Comment by alefragnani** [comment]
Hi @mrkafk ,

Is it happening only with this extension? Did you _closed and reopened_ the VS Code instance, or simply _reloaded_, clicking the Button? 

I'm asking because the _installation/update_ process is not controlled by the extension, but by VS Code itself. In fact, is up to `vsce` to package the extension contents. Also, there was a significant change in version 0.15.0, which is the TypeScript and VSCode engine updates. It now uses TypeScript 2.3.2. Maybe something related to that could be avoiding it to property install the extension.

Hope this helps.

**Comment by mrkafk** [comment]
I have closed and reopened vscode many times, as well as pushed Reload button multiple times.

I have also uninstalled the extension and tried to install it again. I went so far as to move my vscode user folders (like 'Code - OSS' and others residing in %HOME%) elsewhere and tried reinstalling on freshly started, blank instance. Every time the effect was the same.

**Comment by alefragnani** [comment]
Did you see if there is kore than one folder of the extension, with different versions?

Which other extensions do you have installed?

**Comment by alefragnani** [comment]
Hi @mrkafk , any news about it?
