### ISSUE TITLE
[BUG] - Disappearing Bookmark Icon in VSCode on Mac

### ISSUE THREAD

**Issue by sefatanam** [alefragnani/vscode-bookmarks#722]
**Environment/version**

- Extension version: v13.5.0
<img width="717" alt="Screenshot 2024-05-12 at 2 21 25 PM" src="https://github.com/alefragnani/vscode-bookmarks/assets/37630292/573b7154-0a0f-4995-ab01-16d0ccb3c874">

- VSCode version: 
- OS Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z (5 days ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 22.6.0

**Steps to reproduce**
After a fresh VSCode install on my Mac and when I install additional extensions through Sync Settings then Bookmark Icon get disappears.

**Expected Behavior:**
The icon should remain visible after installing extensions through Sync Settings.
**Additional Information:**
There doesn't seem to be an option to toggle the icon back on once it disappears.

**Comment by quixote1304629** [comment]
me too，
Bookmarks icon is not displayed in the left sidebar

**Comment by danigiorgio** [comment]
This worked for me on Mac

Run the command "Reset View Locations" via Command Palette

**Comment by alefragnani** [comment]
Hi @sefatanam ,

Follow @danigiorgio instructions, and it should work. It has already reported a few times on some of my extensions, like #160, and appears to be a know issue on any extension that contributes Side Bar icons.

If the reset command does not work, you should reinstall the extension. But, be sure to _uninstall_ the extension and close all VS Code windows, because if you don't close VS Code, it won't effectively uninstall the extension but only disable it and reuse it in the next install.

Hope this helps
