### ISSUE TITLE
[FEATURE] - I would love to have a similar extension to this in Azure Data Studio.

### ISSUE THREAD

**Issue by Chewieez** [alefragnani/vscode-bookmarks#725]
I've enjoyed using this Bookmarks extension in VS Code and I frequently wish I had a similar extension in Azure Data Studio when working in large .sql files.

**Comment by alefragnani** [comment]
Hi @Chewieez ,

Have you tried to install the extension in ADS, using the [instructions](https://github.com/microsoft/azuredatastudio/wiki/List-of-Extensions#download-steps)? The `.vsix` file is available in the VS Code Marketplace page (https://marketplace.visualstudio.com/). I remember some of my extensions worked on it, when I discovered about ADS, but I'm not entirely sure which one.

ADS itself has no marketplace, and any third party extension must be contributed directly to ADS. There is an open issue in the ADS repo (https://github.com/microsoft/azuredatastudio/issues/3874) asking for an improvement in the extension marketplace, but I'm not sure about ETA. 

I'll wait until ADS has a smoother marketplace experience, in order to try out porting Bookmarks to it.

Hope this helps

**Comment by Chewieez** [comment]
Whoa, I never thought to try installing a VS Code extension into ADS. It makes sense now that I think about it. 

It does work just by installing it in ADS. There is no area to the left of the editor for breakpoints so you need to right click inside the text area to toggle a bookmark, or use the keyboard shortcut. But once you have a bookmark, navigating to it and deleting it via the sidebar tab works normally.

Thanks for the tip!

**Comment by alefragnani** [comment]
That's probably because ADS uses an outdated VS Code version, which does not yet support context menu in gutter. And also, ADS may have its own extensibility and some features may not be available/supported.

Lets wait and see how it evolve in the future
