### ISSUE TITLE
i can not find the search function.

### ISSUE THREAD

**Issue by dshawshank** [alefragnani/vscode-bookmarks#726]
1) I didn't find the search bookmark function. If not, can you add one? In the process of browsing and sorting out the source code, there will be many bookmarks, which is inconvenient to find. 

2) Can some bookmark functions be developed to facilitate the sorting process? For example, grouping bookmarks can adjust the order of bookmarks. 

Thank you.

**Comment by alefragnani** [comment]
Hi @dshawshank ,

In order to search/find for bookmarks, you may use two different commands:

* `Bookmarks: List` List all bookmarks in the current file
* `Bookmarks: List from All Files` List all bookmarks from all files

About the sorting/grouping feature, there are already some issues opened (#254, #435, #183), which I'm planning to deal in upcoming releases. 

Hope this helps
