### ISSUE TITLE
[FEATURE] - Bookmarks not tied to workspace 

### ISSUE THREAD

**Issue by huehnerlady** [alefragnani/vscode-bookmarks#727]
I have bookmarks eg. to my .zshrc or other central files to quickly adapt them when needed. 
Currently I have to add them to every new workspace.

I would love to have the possibility to add specific bookmarks for all workspaces

**Comment by alefragnani** [comment]
Hi @huehnerlady ,

Bookmarks are saved _per session_, so, if you open the same file in different _sessions_ (workspace) the extension will handle them as different bookmarks. That's the reason why you need to add those central files on each workspace. Also, bookmarks are accessible only if the folder containing that file is opened, even on a multi-root workspace.

I think #287 may fit your needs, as the bookmarks wouldn't be saved _per session_ anymore, so whenever you have the file available on the workspace, the bookmark will be available as well.

Otherwise, if all your central files are stored _in the same folder_, currently, as the extension works, you could try combining two concepts:
1. Define the `saveBookmarksInProject` setting as `true`, in order to make the bookmarks to be stored _within the folder_
2. Start using mult-root workspaces (https://code.visualstudio.com/docs/editor/multi-root-workspaces), and add the _central folder_ on every multi-root workspace.
But this would depend on your opennes to adopt multi-root workspaces and it's peculiarites.

Hope this helps

**Comment by huehnerlady** [comment]
I see and I agree that would fix my issue, thanks :)
