### ISSUE TITLE
[BUG] - Missing saved bookmarks in BOOKMARKS: EXPLORER

### ISSUE THREAD

**Issue by Patresko** [alefragnani/vscode-bookmarks#730]
Im using bookmarks in workspace for INTERSYSTEMS IRIS 2024. Bookmarks working fine until I dont close workspace. After reopening workspace once again, I see file where my bookmarks should be, but tree view is empty in explorer and basically I could not navigate through the bookmarks.

![image](https://github.com/alefragnani/vscode-bookmarks/assets/23163555/07ef2617-2046-48ec-b0d2-a79c2fab3f06)

But when I open that file I see bookmarks 

![image](https://github.com/alefragnani/vscode-bookmarks/assets/23163555/8b509682-4149-4e90-89fd-b6f7644a5842)

**Comment by alefragnani** [comment]
Hi @Patresko ,

I'm not familiar with Intersystems Iris 2024, but looking at the VS Marketplace, it seems some extensions defines a _new file system_ in order to work with those files. 

If you use any specific VS Code extension to deal with those files, please describe it here, so I could take a look in order to identify if it is possible to make the Bookmark extension to support its file system.

On the other hand, if Intersystems Iris 2024 files you work with are just regular files on your hard drive, could you provide more details about the folder / files you open?

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if you have more details to share.

Thanks for your understanding
