### ISSUE TITLE
[BUG] - Save As removes all bookmarks

### ISSUE THREAD

**Issue by ThoughtPhotography** [alefragnani/vscode-bookmarks#759]
For most simple tasks I use _Save As_ for source control, but this causes all bookmarks to be deleted.
If this is intended, please make it optional.

When saving '_filename v2_' as '_filename v3_' etc. I want to keep the same bookmarks

- Extension version: v13.5.0
- VSCode version: Cursor
- OS version: Win 10-64

**Steps to reproduce**

1. Create bookmarks.
2. FIle... Save As...

**Comment by alefragnani** [comment]
Hi @ThoughtPhotography ,

This is not intentional, and unfortunately, there is no fix for this issue. VS Code does not provide a way to know when a `Save As` command is being executed, and without that, there is no way to _transfer_ the bookmarks to the new file. I could make handle the `Rename` command, but `Save As`, not.

I have opened a feature request for such API to the VS Code team, but the request didn't receive enough upvotes from the community, so it was closed.

I'm constantly looking for new APIs in VS Code, and if this one appears in the future, I could use it, but right now, there is nothing I can do.

Hope this helps
