### ISSUE TITLE
How to mark a line?

### ISSUE THREAD

**Issue by vannie1** [alefragnani/vscode-bookmarks#78]
hi,

is there any keyboard action to mark a line? Or can I bookmark a line by mouse?

It would be very useful, when you could combine "search"-function and your bookmark-extension.
Like "bookmark all lines which contain the search string"

Sincerly
Andy

**Comment by alefragnani** [comment]
Hi @vannie1 ,

The command is `Bookmarks: Toggle`, which by default has `Ctrl + Alt + K` as it keybinding. You can't however (for now) to bookmark using the mouse, because it depends on a VSCode API, already mapped in [this issue](https://github.com/alefragnani/vscode-bookmarks/issues/24).

About the _search_ function, you can't do that as well, also because it depends on VSCode API mapped in [this issue](https://github.com/alefragnani/vscode-bookmarks/issues/7).

To have both, first I need that VSCode expands the API.

Hope this helps

**Comment by rbenson** [comment]
>You can't however (for now) to bookmark using the mouse, because it depends on a VSCode API, already mapped in this issue. 

It looks like you added this [functionality some time ago](https://github.com/alefragnani/vscode-bookmarks/blob/master/package.json#L89) (unless I am mis-understanding you

**Comment by alefragnani** [comment]
That was using the _right-button click / context menu_. 
The dependency that I referred to is related to clicking in the gutter, like when you toggle a breakpoint.

**Comment by engr-akramulhoque** [comment]
``<script>
alert("This is an interesting topic");
</script>
