### ISSUE TITLE
Ctrl + Alt + l is a critical key binding in Ubuntu

### ISSUE THREAD

**Issue by petrux** [alefragnani/vscode-bookmarks#79]
`Ctrl + Alt + L` could be critical since is the default `Ubuntu` key binding to lock the screen.
Would it be possible to change it?

https://github.com/alefragnani/vscode-bookmarks/blob/288322900dc31333f631db7d515fd4b07e0f313e/package.json#L138

**Comment by alefragnani** [comment]
Hi @petrux ,

I'm sorry to hear that, but unfortunately I can't change the keybinding because it would break other users that are using it today. 

I already received this kind of feedback from other users, and so I decided, sometime ago, take a new approach while creating new commands. _Don't add keybindings_! Simply because of this kind of conflicts, OS and Keyboard Layout related.

Since VS Code itself allows you to customize the keybinding for any command, I suggest you to do this for this command.

Hope this helps.

**Comment by petrux** [comment]
I totally see your point. On my side, I just changed the default binding and everything works fine. Thanks!
