### ISSUE TITLE
Unable to disable Treeview

### ISSUE THREAD

**Issue by jtokoph** [alefragnani/vscode-bookmarks#83]
I like to leave my side bar strictly for the explorer. I can't seem to find an option to disable the Treeview. I think it would be great if the Treeview only showed up if you had an active bookmark.

**Comment by alefragnani** [comment]
Hi @jtokoph ,

I didn't know it was possible when I added the feature. That's why I didn't add a setting for that. But looking deeper now, I found a way to do that, so yes, it would be easy to add 😄.

Unfortunately, I can't focus on this right now (other priorities), so in the meantime, you could Hide it using the context menu in the explorer panel.

Hope this helps.

**Comment by jtokoph** [comment]
I feel like a big dope right now for not even trying to right click on it. :D Thanks for pointing it out!
